import { find, get } from 'lodash';
import { ComplianceSidebarPayload, ComplianceSidebarQuestion, ComplianceSidebarSection, CurrentAIStatusPayload, MQTTComplianceManagerPayload } from '@coldpbc/interfaces';

export const getSectionGroupList = (args: any): MQTTComplianceManagerPayload => {
	const name = get(args, 'name', '');
	const mockData: MQTTComplianceManagerPayload[] = [
		{
			statuses: [],
			compliance_definition: {
				name: 'rei_pia_2024',
				title: 'REI Product Impact Assessment 2024',
				version: 2024,
				logo_url: 'https://cold-public-assets.s3.us-east-2.amazonaws.com/3rdPartyLogos/compliance_svgs/rei_logo.svg',
				image_url: 'https://cold-public-assets.s3.us-east-2.amazonaws.com/complianceBackgroundImages/rei.png',
				compliance_section_groups: [
					{
						id: 'csg_u52xp76tclba5djc',
						order: 1,
						title: 'D & I',
						metadata: null,
						compliance_definition_name: 'rei_pia_2024',
					},
					{
						id: 'csg_mnjg81nrtfgsphp4',
						order: 2,
						title: 'Practices',
						metadata: null,
						compliance_definition_name: 'rei_pia_2024',
					},
					{
						id: 'csg_gnawsv7bv67xumws',
						order: 4,
						title: 'Product',
						metadata: null,
						compliance_definition_name: 'rei_pia_2024',
					},
				],
				metadata: {
					term: 'annual',
					due_date: '2024-03-09T00:00:00.00',
				},
			},
		},
	];
	const found = find(mockData, item => item.compliance_definition.name === name);
	return found || mockData[0];
};

export const getSectionList = (args: any) => {
	const name = get(args, 'name', '');
	const sectionGroupId = get(args, 'sectionGroupId', '');
	const mockData = [
		{
			name: 'rei_pia_2024',
			section_groups: [
				{
					sectionGroupId: 'csg_u52xp76tclba5djc',
					sections: [
						{
							id: 'cs_g5prbr04liwq2iy6',
							key: 'INC',
							title: 'Diversity & Inclusion: General',
							metadata: null,
							order: 17,
							compliance_section_group_id: 'csg_u52xp76tclba5djc',
							compliance_definition_name: 'rei_pia_2024',
							_count: {
								compliance_questions: 6,
							},
						},
						{
							id: 'cs_m85htg8kkj8psfbc',
							key: 'MKT',
							title: 'Diversity & Inclusion: Marketing Diversity',
							metadata: null,
							order: 12,
							compliance_section_group_id: 'csg_u52xp76tclba5djc',
							compliance_definition_name: 'rei_pia_2024',
							_count: {
								compliance_questions: 3,
							},
						},
						{
							id: 'cs_mlwf1rptdl1nf0f5',
							key: 'APP',
							title: 'Diversity & Inclusion: Cultural Appropriation',
							metadata: null,
							order: 11,
							compliance_section_group_id: 'csg_u52xp76tclba5djc',
							compliance_definition_name: 'rei_pia_2024',
							_count: {
								compliance_questions: 2,
							},
						},
						{
							id: 'cs_oqro7y64jpwjauar',
							key: 'COL',
							title: 'Diversity & Inclusion: Inclusive Colorways',
							metadata: null,
							order: 14,
							compliance_section_group_id: 'csg_u52xp76tclba5djc',
							compliance_definition_name: 'rei_pia_2024',
							_count: {
								compliance_questions: 2,
							},
						},
						{
							id: 'cs_pjmqyrrfzbtqvbi7',
							key: 'COP',
							title: 'Diversity & Inclusion: Inclusive Copy',
							metadata: null,
							order: 13,
							compliance_section_group_id: 'csg_u52xp76tclba5djc',
							compliance_definition_name: 'rei_pia_2024',
							_count: {
								compliance_questions: 2,
							},
						},
						{
							id: 'cs_r8wflfvf7o7tfm2q',
							key: 'ISS',
							title: 'Diversity & Inclusion: Inclusive Sizing',
							metadata: null,
							order: 15,
							compliance_section_group_id: 'csg_u52xp76tclba5djc',
							compliance_definition_name: 'rei_pia_2024',
							_count: {
								compliance_questions: 2,
							},
						},
						{
							id: 'cs_v7aqyq1r17ndfh2i',
							key: 'DHT',
							title: 'Diversity & Inclusion: Diverse Hair Type Inclusion',
							metadata: null,
							order: 16,
							compliance_section_group_id: 'csg_u52xp76tclba5djc',
							compliance_definition_name: 'rei_pia_2024',
							_count: {
								compliance_questions: 1,
							},
						},
					],
				},
				{
					sectionGroupId: 'csg_mnjg81nrtfgsphp4',
					sections: [
						{
							id: 'cs_a6ggbg5yueu9h3x9',
							key: 'MFG',
							title: 'Manufacturing Code of Conduct & Responsible Sourcing',
							metadata: null,
							order: 1,
							compliance_section_group_id: 'csg_mnjg81nrtfgsphp4',
							compliance_definition_name: 'rei_pia_2024',
							_count: {
								compliance_questions: 15,
							},
						},
						{
							id: 'cs_pfcuqh8485r84svr',
							key: 'GEN',
							title: 'Brand Information',
							metadata: null,
							order: 0,
							compliance_section_group_id: 'csg_mnjg81nrtfgsphp4',
							compliance_definition_name: 'rei_pia_2024',
							_count: {
								compliance_questions: 11,
							},
						},
						{
							id: 'cs_pj88et1zsce8ubf1',
							key: 'CRP',
							title: 'Core Practices',
							metadata: null,
							order: 22,
							compliance_section_group_id: 'csg_mnjg81nrtfgsphp4',
							compliance_definition_name: 'rei_pia_2024',
							_count: {
								compliance_questions: 6,
							},
						},
					],
				},
				{
					sectionGroupId: 'csg_gnawsv7bv67xumws',
					sections: [
						{
							id: 'cs_hy7ogimm4bfnzvy9',
							key: 'PRD',
							title: 'Product Care, Repair, Reuse & End-of-life',
							metadata: null,
							order: 21,
							compliance_section_group_id: 'csg_gnawsv7bv67xumws',
							compliance_definition_name: 'rei_pia_2024',
							_count: {
								compliance_questions: 7,
							},
						},
						{
							id: 'cs_iwm8sg46j8thawb3',
							key: 'PSA',
							title: 'Product Sustainability & Preferred Attributes',
							metadata: null,
							order: 18,
							compliance_section_group_id: 'csg_gnawsv7bv67xumws',
							compliance_definition_name: 'rei_pia_2024',
							_count: {
								compliance_questions: 3,
							},
						},
						{
							id: 'cs_uooqzhc9ibc5uaaw',
							key: 'APK',
							title: 'Packaging - Apparel',
							metadata: null,
							order: 20,
							compliance_section_group_id: 'csg_gnawsv7bv67xumws',
							compliance_definition_name: 'rei_pia_2024',
							_count: {
								compliance_questions: 6,
							},
						},
						{
							id: 'cs_zjxjwkrlqbkkl7e6',
							key: 'PKG',
							title: 'Packaging - General',
							metadata: null,
							order: 19,
							compliance_section_group_id: 'csg_gnawsv7bv67xumws',
							compliance_definition_name: 'rei_pia_2024',
							_count: {
								compliance_questions: 4,
							},
						},
					],
				},
			],
		},
	];
	// find mock data by compliance_definition_name and compliance_section_group_id
	const complianceData = find(mockData, item => item.name === name);
	if (!complianceData) return [];
	const sectionGroupData = find(complianceData.section_groups, group => group.sectionGroupId === sectionGroupId);
	if (!sectionGroupData) return [];
	return [sectionGroupData.sections[0]];
};

export const getQuestionList = (args: any): ComplianceSidebarPayload | undefined => {
	const name = get(args, 'name', '');
	const sectionGroupId = get(args, 'sectionGroupId', '');
	const mockData = [
		{
			name: 'rei_pia_2024',
			section_groups: [
				{
					sectionGroupId: 'csg_u52xp76tclba5djc',
					sections: [
						{
							id: 'cs_g5prbr04liwq2iy6',
							key: 'INC',
							title: 'Diversity & Inclusion: General',
							questions: [
								{
									id: 'cq_f8hasmaft6xxu0uw',
									prompt: 'Does your policy explicitly prohibit discrimination based on both sexual orientation and gender identity?',
									order: 82,
									key: 'INC-2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_fl5vwy0ods15a0tb',
									prompt:
										'This subset of questions is related to diversity, equity and inclusion practices at your organization, not limited to the product space. As REI seeks to progress a more inclusive outdoor industry, we are hoping to understand where brands are at.\n\nDoes your brand have a policy/policies in place regarding nondiscrimination as related to employment, customer service, grant-making or other areas?',
									order: 81,
									key: 'INC-1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_gataayg43kzordz5',
									prompt: 'Please select one the following to describe the reach of your nondiscrimination policy.',
									order: 83,
									key: 'INC-3',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_l8e7di1bysiv7lss',
									prompt: 'Does your brand have in place a policy or practice for pay equity across gender and race?',
									order: 85,
									key: 'INC-5',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_qhoomtjw9ef00ao5',
									prompt: 'Does your brand have in place a policy for healthcare explicitly inclusive of the LGBTQ+ community?',
									order: 86,
									key: 'INC-6',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_u21jqrm4u6l2forz',
									prompt: "Does your brand have/plan to create product that is designed beyond the gender binary (i.e. not women or men's only)?",
									order: 84,
									key: 'INC-4',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
							],
						},
						{
							id: 'cs_m85htg8kkj8psfbc',
							key: 'MKT',
							title: 'Diversity & Inclusion: Marketing Diversity',
							questions: [
								{
									id: 'cq_hpc48itscepqkdg6',
									prompt: 'What strategies is your brand currently using as part of its guidelines?',
									order: 72,
									key: 'MKT-2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_luyd6oh0w1d7leqj',
									prompt: 'Which dimensions of diversity or other topics do your guidelines address?',
									order: 73,
									key: 'MKT-3',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_v7b6hyqg3gfjs489',
									prompt:
										'The REI Product Impact Standards include the expectation that each brand partner has in place guidelines for marketing assets, photo casting and production that ensure diverse and inclusive representation across race, age, gender identity/expression, body size and disability. Content supplied to REI by influencers and affiliate media, as well as photography, marketing copy, and other content, shall reflect the same inclusive representation.\n\nWhich option below best describes your brand’s status, as of Spring 2023 product lines and marketing, in addressing diverse and inclusive representation in its marketing and photo casting?',
									order: 71,
									key: 'MKT-1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
							],
						},
						{
							id: 'cs_mlwf1rptdl1nf0f5',
							key: 'APP',
							title: 'Diversity & Inclusion: Cultural Appropriation',
							questions: [
								{
									id: 'cq_ho1blgggzk8gat67',
									prompt:
										'As part of the REI Product Impact Standards, REI has established several expectations related to diversity and inclusion that we would like brand partners to implement. The following questions are intended to understand brand partners’ current state in implementing these practices.\n\nThe REI Product Impact Standards include the expectation that each brand partner has in place creative controls to prevent cultural appropriation: plagiarism, theft and/or inappropriate use of designs, patterns, forms, materials, words/names, etc. that are culturally meaningful to and/or originated from underrepresented communities. These creative controls should ensure that the development of products, promotions, and marketing used during annual cultural moments (e.g., Pride, Black History Month etc.) is shaped by members of the represented communities.\n\nWhich option below best describes how your brand is actively mitigating cultural appropriation, as of Spring 2024 product lines and marketing?',
									order: 69,
									key: 'APP-1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_pu6sv6tnp6yl1n2m',
									prompt: 'Which creative controls is your brand currently using to prevent cultural appropriation?',
									order: 70,
									key: 'APP-2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
							],
						},
						{
							id: 'cs_oqro7y64jpwjauar',
							key: 'COL',
							title: 'Diversity & Inclusion: Inclusive Colorways',
							questions: [
								{
									id: 'cq_f3dxwn3f574wygse',
									prompt:
										'The REI Product Impact Standards include the expectation that all wearable products supplied to REI be available in colorways appropriate for a range of skin tones/complexions; and that product marketed as ‘Nude’ including those with embellishments and/or linings intended to give the impression of bare skin or to mimic skin tone, be available in a range of tones.\n\nWhich of the following describes the active creative controls your brand has in place to ensure colorways of wearable products are appropriate for a variety of skin tones/complexions?',
									order: 76,
									key: 'COL-1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_ixp28a5byvxdahil',
									prompt: 'Which of the following strategies is your brand currently using to address inclusion in its color offering?',
									order: 77,
									key: 'COL-2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
							],
						},
						{
							id: 'cs_pjmqyrrfzbtqvbi7',
							key: 'COP',
							title: 'Diversity & Inclusion: Inclusive Copy',
							questions: [
								{
									id: 'cq_dbgc6e8e6tjff69o',
									prompt: 'Which of the following policies or creative controls do you utilize as it relates to inclusive product copy?',
									order: 75,
									key: 'COP-2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_eymywin27r7sql7t',
									prompt:
										'The REI Product Impact Standards include the expectation that each brand partner has in place creative controls to prevent the use of language in naming conventions (as applied to product, collection, color, or design); product information; marketing assets, etc., that negatively impact underrepresented groups (e.g., by reinforcing stereotypes, utilizing slurs, coopting cultural language, etc.).\n\nDoes your brand currently have in place policies or creative controls related to inclusive product copy?',
									order: 74,
									key: 'COP-1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
							],
						},
						{
							id: 'cs_r8wflfvf7o7tfm2q',
							key: 'ISS',
							title: 'Diversity & Inclusion: Inclusive Sizing',
							questions: [
								{
									id: 'cq_mc4fi040gdht0ujm',
									prompt:
										'The REI Product Impact Standards has an expectation that all brand partners who sell wearable products offered in a variety of sizes maintain the same price within a style regardless of size. \n\nDoes your brand currently maintain the same price across wearable products offered in a variety of sizes regardless of size?',
									order: 79,
									key: 'ISS-2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_roa9rjksxxga0fg3',
									prompt:
										'The REI Product Impact Standard has an expectation that each brand partner that sells wearable products offered in a variety of sizes to provide REI at least one sample size outside the standard size range for marketing photography. \n\nAs a standard practice, does your brand currently send REI at least one sample size outside the standard size range for marketing photography of wearable products?',
									order: 78,
									key: 'ISS-1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
							],
						},
						{
							id: 'cs_v7aqyq1r17ndfh2i',
							key: 'DHT',
							title: 'Diversity & Inclusion: Diverse Hair Type Inclusion',
							questions: [
								{
									id: 'cq_qvh3x3qxik3ov5cf',
									prompt:
										'The REI Product Impact Standards has an expectation that each brand partner that produces headwear (helmets, hats, headbands, hoods, balaclavas, hijab, etc.) to have in place guidelines for ensuring an inclusive assortment for a variety of hair types, including higher-volume and textured hair.\n\nWhich of the below options best represents how your brand is approaching the Diverse Hair Type Inclusion expectation?',
									order: 80,
									key: 'DHT-1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
							],
						},
					],
				},
				{
					sectionGroupId: 'csg_mnjg81nrtfgsphp4',
					sections: [
						{
							id: 'cs_a6ggbg5yueu9h3x9',
							key: 'MFG',
							title: 'Manufacturing Code of Conduct & Responsible Sourcing',
							questions: [
								{
									id: 'cq_u652y5x985xki3b5',
									prompt: 'Does your brand have in place a code of conduct for factories that manufacture the products you supply to REI?',
									order: 11,
									key: 'MFG-0',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_h9f68m5chgu5pyd9',
									prompt: 'Is your brand’s supplier list publicly available?',
									order: 22,
									key: 'MFG-8',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_i7k4mphvwp63ivw9',
									prompt: 'Does your brand have a formal process for utilizing social and/or environmental performance data in sourcing decisions?',
									order: 24,
									key: 'MFG-10',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_g5by322p9fd7t70j',
									prompt: 'Does your brand have an ongoing training program(s) for suppliers to promote improved sustainability performance within your supply chain?',
									order: 25,
									key: 'MFG-11',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
							],
						},
						{
							id: 'cs_pfcuqh8485r84svr',
							key: 'GEN',
							title: 'Brand Information',
							questions: [
								{
									id: 'cq_jx434i4vqjr8343j',
									prompt: 'What is your REI Vendor ID?',
									order: 0,
									key: 'GEN-0:1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_xdymanb0bzyt7fkh',
									prompt: 'What is your Vendor Name?',
									order: 1,
									key: 'GEN-0:2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_ws0dm3v0h78fnq2c',
									prompt: 'For which brand(s) are you completing the assessment?',
									order: 2,
									key: 'GEN-0:3',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_icdankdifllufvr4',
									prompt: 'List the name, email, and title of the person completing this assessment.',
									order: 3,
									key: 'GEN-1:1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_mg9kedhrof7vgw56',
									prompt: "List your brand's Product Sustainability Contact, if different from your response in the previous question",
									order: 4,
									key: 'GEN-1:2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_y4jjgljfwybit94k',
									prompt: "List your brand's Diversity, Equity, & Inclusion (DEI) Contact, if different from your response in the previous question(s)",
									order: 5,
									key: 'GEN-1:3',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_ds6c51gxm6hnj21f',
									prompt: 'List any additional contacts for Product Sustainability',
									order: 6,
									key: 'GEN-1:4',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_a7uxoplkyque9thu',
									prompt: 'List any additional contacts for Diversity, Equity, & Inclusion (DEI)',
									order: 7,
									key: 'GEN-1:5',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_vs46jzwxbq58q8ei',
									prompt: 'List any additional contacts that supported filling out this assessment',
									order: 8,
									key: 'GEN-1:6',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_pxk6p3b3sj7kz6i7',
									prompt: 'How many employees, if any, are currently dedicated to product sustainability at your brand?',
									order: 9,
									key: 'GEN-2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_siap0pl9v0lda4eh',
									prompt:
										'Please indicate if your brand has supplied to REI in the past 12 months, or anticipates supplying to REI in the next 12 months, products that fall into any of the following categories.',
									order: 10,
									key: 'GEN-3',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
							],
						},
						{
							id: 'cs_pj88et1zsce8ubf1',
							key: 'CRP',
							title: 'Core Practices',
							questions: [
								{
									id: 'cq_l60noewfxpddnda9',
									prompt: 'Is your brand an active member of or participant in any of the following globally recognized sustainability forums?',
									order: 107,
									key: 'CRP-1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_seoqoexyy8wf0ybr',
									prompt: 'Does your brand have an ongoing commitment to donating a specific portion of your sales or profits to philanthropic causes?',
									order: 108,
									key: 'CRP-2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_rww6hu1j1qw9upn4',
									prompt:
										'Does your brand publish regular public-facing updates on your sustainability commitments and progress toward those commitments (e.g., annual sustainability report)?',
									order: 109,
									key: 'CRP-3',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_kcv8g80wbzvtj2i4',
									prompt:
										'(Optional) We want to explore ways we can best convene and support you and other brands we work with to deliver more inclusive and culturally relevant offerings to our customer, and extend positive impacts to the broader community. What practices, information, or other resources would you be interested in?',
									order: 110,
									key: 'CRP-4',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_ofzftnxtwwahylxo',
									prompt:
										'(Optional) As part of our ongoing support, we have offered various resources including virtual trainings, panels, and an inclusive design playbook. If you or your team have utilized or attended any of these resources/events, what was helpful and what would you like to see more of?',
									order: 111,
									key: 'CRP-5',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_k68ra2udf83t5v9h',
									prompt: '(Optional) If there are any other general comments or questions you would like to share with REI regarding product impact, please enter them below.',
									order: 112,
									key: 'CRP-6',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
							],
						},
					],
				},
				{
					sectionGroupId: 'csg_gnawsv7bv67xumws',
					sections: [
						{
							id: 'cs_hy7ogimm4bfnzvy9',
							key: 'PRD',
							title: 'Product Care, Repair, Reuse & End-of-life',
							questions: [
								{
									id: 'cq_fvsbqaiye12ovk1i',
									prompt: 'Does your brand provide customers with guidance for how to use and care for your product in an environmentally responsible manner?',
									order: 100,
									key: 'PRD-1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_jsfz7wpqo4madvw0',
									prompt: 'Does your brand offer a lifetime warranty for products?',
									order: 101,
									key: 'PRD-2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_k0yj0tj16u06m5mj',
									prompt: 'Are the repairs conducted in-house or through a third-party?',
									order: 103,
									key: 'PRD-4',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_qf8p0hurvwx9b6ry',
									prompt: 'Does your brand offer solutions for your customers to donate and/or recycle products at end-of-life?',
									order: 106,
									key: 'PRD-7',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_u5lxsshxa4z88sgn',
									prompt: 'Does your brand provide product repair services to your customers?',
									order: 102,
									key: 'PRD-3',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_xl9iogy4kp764qyf',
									prompt: 'Does your brand sell used products?',
									order: 104,
									key: 'PRD-5',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_yga8el7bq1j2roji',
									prompt: 'Does your brand rent or lease products to your customers?',
									order: 105,
									key: 'PRD-6',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
							],
						},
						{
							id: 'cs_iwm8sg46j8thawb3',
							key: 'PSA',
							title: 'Product Sustainability & Preferred Attributes',
							questions: [
								{
									id: 'cq_d5ll8h676h6707xp',
									prompt: "Please select which of REI's preferred sustainability attributes your brand has policies or targets in place for (if any)",
									order: 88,
									key: 'PSA-2:1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_h9y6wqh1se68lnr2',
									prompt: 'For the ones you have policies or targets in place for, please select ones where the policies or targets are publicly available.',
									order: 89,
									key: 'PSA-2:2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_ppu9hzo3bafupmc6',
									prompt: 'Does your brand utilize a formal methodology or tool to measure the sustainability of your materials and/or finished products?',
									order: 87,
									key: 'PSA-1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
							],
						},
						{
							id: 'cs_uooqzhc9ibc5uaaw',
							key: 'APK',
							title: 'Packaging - Apparel',
							questions: [
								{
									id: 'cq_d7yrh6borz2oyvmk',
									prompt:
										'REI’s Vendor Guide indicates that brands shipping non-white apparel items to REI should do so without individual polybags. Brands will be charged a $.01/unit polybag recycling fee for apparel items arriving in individual polybags at an REI receiving location. Please refer to REI’s Vendor Guide (available on the REI Partners Site) for more information.\n\nApproximately what percentage of the apparel product units your brand shipped to REI during the past calendar year were packaged in individual polybags?',
									order: 94,
									key: 'APK-1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_n1fry37w1irxojkx',
									prompt:
										'As of the Spring 2024 product season, have you implemented as your standard practice the shipment of non-white apparel products to REI without the use of individual polybags?',
									order: 98,
									key: 'APK-5',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_o8hr1vgm4q4zzwxe',
									prompt:
										'Approximately what percentage of the apparel product units your brand shipped to REI during the past calendar year were packaged in a master polybag containing all units in each carton?',
									order: 95,
									key: 'APK-2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_p932mlspe841elr7',
									prompt: 'If you ship apparel items to REI without individual polybags, how are they packaged?',
									order: 96,
									key: 'APK-3',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_pemwl83szaok5evo',
									prompt: 'Approximately what percentage of the apparel product units that you ship to REI during the coming year will be packaged in individual polybags?',
									order: 97,
									key: 'APK-4',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_rvdeuwgjjno3mc6k',
									prompt:
										'If your brand is unable to ship non-white apparel items to REI without the use of individual polybags, please describe the key factors that prevent you from doing so.',
									order: 99,
									key: 'APK-6',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
							],
						},
						{
							id: 'cs_zjxjwkrlqbkkl7e6',
							key: 'PKG',
							title: 'Packaging - General',
							questions: [
								{
									id: 'cq_d8yncydlvqv12fnh',
									prompt: 'Has your brand been able to phase out the use of single-use plastics across any noteworthy areas of primary or secondary product packaging?',
									order: 92,
									key: 'PKG-2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_eh4nivkqk4p6dip6',
									prompt: 'Please indicate whether your brand has formal policies/targets in place regarding the use of more sustainable product packaging.',
									order: 90,
									key: 'PKG-1:1',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_fsga7wa1g0yio647',
									prompt: 'Are there other best sustainability practices for primary product packaging that you have in place that you’d like to share with REI?',
									order: 93,
									key: 'PKG-3',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
								{
									id: 'cq_lrpqk7q5e9uzlh5q',
									prompt: 'For the ones you have policies or targets in place for, please select ones where the policies or targets are publicly available.',
									order: 91,
									key: 'PKG-1:2',
									organization_id: 'org_VWv3Al9pLEI4CaOH',
									not_started: true,
									ai_answered: false,
									user_answered: false,
									bookmarked: false,
								},
							],
						},
					],
				},
			],
		},
	];

	// get the questions by compliance_definition_name, compliance_section_group_id, and section_id
	const complianceData = find(mockData, item => item.name === name);
	if (!complianceData) return undefined;
	const sectionGroupData = find(complianceData.section_groups, group => group.sectionGroupId === sectionGroupId);
	if (!sectionGroupData) return undefined;
	const sectionData = sectionGroupData.sections[0];
	if (!sectionData) return undefined;

	return {
		name: name,
		compliance_section_groups: [
			{
				id: sectionGroupData.sectionGroupId,
				title: 'D & I',
				order: 0,
				compliance_sections: [
					{
						id: sectionData.id,
						key: sectionData.key,
						title: sectionData.title,
						order: 15,
						compliance_questions: sectionData.questions,
					},
				],
			},
		],
	};
};

export const getComplianceSectionProgressBarQuestionsMock = (): ComplianceSidebarQuestion[] => {
	return [
		{
			id: 'cq_d7yrh6borz2oyvmk',
			prompt:
				'REI’s Vendor Guide indicates that brands shipping non-white apparel items to REI should do so without individual polybags. Brands will be charged a $.01/unit polybag recycling fee for apparel items arriving in individual polybags at an REI receiving location. Please refer to REI’s Vendor Guide (available on the REI Partners Site) for more information.\n\nApproximately what percentage of the apparel product units your brand shipped to REI during the past calendar year were packaged in individual polybags?',
			order: 94,
			key: 'APK-1',
			not_started: true,
			ai_answered: false,
			user_answered: false,
			bookmarked: false,
		},
		{
			id: 'cq_n1fry37w1irxojkx',
			prompt:
				'As of the Spring 2024 product season, have you implemented as your standard practice the shipment of non-white apparel products to REI without the use of individual polybags?',
			order: 98,
			key: 'APK-5',
			not_started: false,
			ai_answered: true,
			user_answered: false,
			bookmarked: false,
		},
		{
			id: 'cq_o8hr1vgm4q4zzwxe',
			prompt:
				'Approximately what percentage of the apparel product units your brand shipped to REI during the past calendar year were packaged in a master polybag containing all units in each carton?',
			order: 95,
			key: 'APK-2',
			not_started: false,
			ai_answered: false,
			user_answered: true,
			bookmarked: false,
		},
		{
			id: 'cq_p932mlspe841elr7',
			prompt: 'If you ship apparel items to REI without individual polybags, how are they packaged?',
			order: 96,
			key: 'APK-3',
			not_started: false,
			ai_answered: false,
			user_answered: true,
			bookmarked: false,
		},
		{
			id: 'cq_pemwl83szaok5evo',
			prompt: 'Approximately what percentage of the apparel product units that you ship to REI during the coming year will be packaged in individual polybags?',
			order: 97,
			key: 'APK-4',
			not_started: false,
			ai_answered: false,
			user_answered: false,
			bookmarked: true,
		},
		{
			id: 'cq_rvdeuwgjjno3mc6k',
			prompt:
				'If your brand is unable to ship non-white apparel items to REI without the use of individual polybags, please describe the key factors that prevent you from doing so.',
			order: 99,
			key: 'APK-6',
			not_started: false,
			ai_answered: false,
			user_answered: false,
			bookmarked: true,
		},
	];
};

export const getComplianceManagerOverviewSectionsMock = (): ComplianceSidebarSection => {
	return {
		id: 'cs_e1p1fo2i6mnvv0nn',
		key: 'CHEM',
		title: 'Diversity & Inclusion: Inclusive Sizing',
		order: 15,
		compliance_questions: [
			{
				id: 'cq_d2cmihcr4mwpn2sa',
				prompt: 'Please specify which third-party RSL(s).',
				order: 30,
				key: 'CHEM-3A',
				not_started: false,
				ai_answered: true,
				user_answered: false,
				bookmarked: false,
			},
			{
				id: 'cq_jba9yyibiexy6zx7',
				prompt: 'Is your brand’s RSL publicly available?',
				order: 31,
				key: 'CHEM-4',
				not_started: true,
				ai_answered: false,
				user_answered: false,
				bookmarked: false,
			},
			{
				id: 'cq_pvz2w191snt5jwu4',
				prompt: 'Does your brand have a means of verifying that products you supply to REI comply with your RSL?',
				order: 27,
				key: 'CHEM-1',
				not_started: false,
				ai_answered: true,
				user_answered: false,
				bookmarked: false,
			},
			{
				id: 'cq_v8379scq7pncl3d5',
				prompt: 'Is your RSL aligned to an internationally recognized third-party RSL?',
				order: 29,
				key: 'CHEM-3',
				not_started: false,
				ai_answered: false,
				user_answered: true,
				bookmarked: false,
			},
			{
				id: 'cq_wu2kksbvijpxmyc3',
				prompt:
					'As part of the REI Product Impact Standards, REI expects each brand partner to have in place a Restricted Substances List (RSL) that specifies which substances are banned or restricted in products and that meets or exceeds all applicable regulatory requirements.\n\nDoes your brand have an RSL in place for the products you supply to REI?',
				order: 26,
				key: 'CHEM-0',
				not_started: false,
				ai_answered: true,
				user_answered: false,
				bookmarked: false,
			},
			{
				id: 'cq_y5ar15bfkrud9ysx',
				prompt: 'Please indicate whether your brand’s chemicals management program consists of the following components that aid in verifying compliance with your RSL.',
				order: 28,
				key: 'CHEM-2',
				not_started: false,
				ai_answered: true,
				user_answered: false,
				bookmarked: false,
			},
		],
	};
};

export const getComplianceManagerOverviewAIProgressPercentageMock = (): CurrentAIStatusPayload => {
	return [
		{
			section: 'GEN',
			questions: [],
		},
		{
			section: 'CRP',
			questions: [],
		},
		{
			section: 'WL',
			questions: [],
		},
		{
			section: 'FR',
			questions: [],
		},
		{
			section: 'CHEM',
			questions: [],
		},
		{
			section: 'MFG',
			questions: [],
		},
		{
			section: 'GHG',
			questions: [],
		},
		{
			section: 'PRD',
			questions: [],
		},
	];
};
