import { find, get } from 'lodash';
import { MQTTComplianceManagerPayload, MQTTComplianceManagerPayloadComplianceQuestionList } from '@coldpbc/interfaces';

export const getSectionGroupList = (args: any): MQTTComplianceManagerPayload => {
  const name = get(args, 'name', '');
  const mockData: MQTTComplianceManagerPayload[] = [
    {
      statuses: [],
      compliance_definition: {
        name: 'rei_pia_2024',
        title: 'REI Product Impact Assessment 2024',
        version: 2024,
        logo_url: 'https://cold-public-assets.s3.us-east-2.amazonaws.com/3rdPartyLogos/compliance_svgs/rei_logo.svg',
        image_url: 'https://cold-public-assets.s3.us-east-2.amazonaws.com/complianceBackgroundImages/rei.png',
        compliance_section_groups: [
          {
            id: 'csg_ual97c2pos346hkf',
            order: 0,
            title: 'Materials',
            metadata: null,
            compliance_definition_name: 'rei_pia_2024',
          },
          {
            id: 'csg_u52xp76tclba5djc',
            order: 1,
            title: 'D & I',
            metadata: null,
            compliance_definition_name: 'rei_pia_2024',
          },
          {
            id: 'csg_mnjg81nrtfgsphp4',
            order: 2,
            title: 'Practices',
            metadata: null,
            compliance_definition_name: 'rei_pia_2024',
          },
          {
            id: 'csg_xcv2gzlmrrucrzr5',
            order: 3,
            title: 'Environment',
            metadata: null,
            compliance_definition_name: 'rei_pia_2024',
          },
          {
            id: 'csg_gnawsv7bv67xumws',
            order: 4,
            title: 'Product',
            metadata: null,
            compliance_definition_name: 'rei_pia_2024',
          },
        ],
        metadata: {
          term: 'annual',
          due_date: '2024-03-09T00:00:00.00',
        },
      },
    },
  ];
  const found = find(mockData, item => item.compliance_definition.name === name);
  return found || mockData[0];
};

export const getSectionList = (args: any) => {
  const name = get(args, 'name', '');
  const sectionGroupId = get(args, 'sectionGroupId', '');
  const mockData = [
    {
      name: 'rei_pia_2024',
      section_groups: [
        {
          sectionGroupId: 'csg_ual97c2pos346hkf',
          sections: [
            {
              id: 'cs_cr9ud1djx1h7xrem',
              key: 'WL',
              title: 'Wool',
              metadata: null,
              order: 9,
              compliance_section_group_id: 'csg_ual97c2pos346hkf',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 2,
              },
            },
            {
              id: 'cs_fkhppv9zp5yk4qg0',
              key: 'FR',
              title: 'Flame Retardant (FR) Chemicals',
              metadata: null,
              order: 7,
              compliance_section_group_id: 'csg_ual97c2pos346hkf',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 3,
              },
            },
            {
              id: 'cs_kvyvslvd8k9b6u9l',
              key: 'CHEM',
              title: 'Restricted Substances List & Chemicals Management',
              metadata: null,
              order: 2,
              compliance_section_group_id: 'csg_ual97c2pos346hkf',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 6,
              },
            },
            {
              id: 'cs_uzcancxkpelymuv9',
              key: 'DWN',
              title: 'Down',
              metadata: null,
              order: 8,
              compliance_section_group_id: 'csg_ual97c2pos346hkf',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 2,
              },
            },
            {
              id: 'cs_v4qmnk2ubja9ko3x',
              key: 'AFL',
              title: 'Animal Fur & Exotic Leather',
              metadata: null,
              order: 10,
              compliance_section_group_id: 'csg_ual97c2pos346hkf',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 3,
              },
            },
            {
              id: 'cs_w3a3maz46vkbwto0',
              key: 'BPA',
              title: 'Bisphenol A',
              metadata: null,
              order: 5,
              compliance_section_group_id: 'csg_ual97c2pos346hkf',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 2,
              },
            },
            {
              id: 'cs_w3yijeqzqzh5z4lw',
              key: 'SUN',
              title: 'Sunscreen Ingredients',
              metadata: null,
              order: 6,
              compliance_section_group_id: 'csg_ual97c2pos346hkf',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 3,
              },
            },
            {
              id: 'cs_xpfz8pcnz5l3q7hn',
              key: 'PFAS',
              title: 'Per- and Polyfluoroalkyl Substances',
              metadata: null,
              order: 4,
              compliance_section_group_id: 'csg_ual97c2pos346hkf',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 2,
              },
            },
          ],
        },
        {
          sectionGroupId: 'csg_u52xp76tclba5djc',
          sections: [
            {
              id: 'cs_g5prbr04liwq2iy6',
              key: 'INC',
              title: 'Diversity & Inclusion: General',
              metadata: null,
              order: 17,
              compliance_section_group_id: 'csg_u52xp76tclba5djc',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 6,
              },
            },
            {
              id: 'cs_m85htg8kkj8psfbc',
              key: 'MKT',
              title: 'Diversity & Inclusion: Marketing Diversity',
              metadata: null,
              order: 12,
              compliance_section_group_id: 'csg_u52xp76tclba5djc',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 3,
              },
            },
            {
              id: 'cs_mlwf1rptdl1nf0f5',
              key: 'APP',
              title: 'Diversity & Inclusion: Cultural Appropriation',
              metadata: null,
              order: 11,
              compliance_section_group_id: 'csg_u52xp76tclba5djc',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 2,
              },
            },
            {
              id: 'cs_oqro7y64jpwjauar',
              key: 'COL',
              title: 'Diversity & Inclusion: Inclusive Colorways',
              metadata: null,
              order: 14,
              compliance_section_group_id: 'csg_u52xp76tclba5djc',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 2,
              },
            },
            {
              id: 'cs_pjmqyrrfzbtqvbi7',
              key: 'COP',
              title: 'Diversity & Inclusion: Inclusive Copy',
              metadata: null,
              order: 13,
              compliance_section_group_id: 'csg_u52xp76tclba5djc',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 2,
              },
            },
            {
              id: 'cs_r8wflfvf7o7tfm2q',
              key: 'ISS',
              title: 'Diversity & Inclusion: Inclusive Sizing',
              metadata: null,
              order: 15,
              compliance_section_group_id: 'csg_u52xp76tclba5djc',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 2,
              },
            },
            {
              id: 'cs_v7aqyq1r17ndfh2i',
              key: 'DHT',
              title: 'Diversity & Inclusion: Diverse Hair Type Inclusion',
              metadata: null,
              order: 16,
              compliance_section_group_id: 'csg_u52xp76tclba5djc',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 1,
              },
            },
          ],
        },
        {
          sectionGroupId: 'csg_mnjg81nrtfgsphp4',
          sections: [
            {
              id: 'cs_a6ggbg5yueu9h3x9',
              key: 'MFG',
              title: 'Manufacturing Code of Conduct & Responsible Sourcing',
              metadata: null,
              order: 1,
              compliance_section_group_id: 'csg_mnjg81nrtfgsphp4',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 15,
              },
            },
            {
              id: 'cs_pfcuqh8485r84svr',
              key: 'GEN',
              title: 'Brand Information',
              metadata: null,
              order: 0,
              compliance_section_group_id: 'csg_mnjg81nrtfgsphp4',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 11,
              },
            },
            {
              id: 'cs_pj88et1zsce8ubf1',
              key: 'CRP',
              title: 'Core Practices',
              metadata: null,
              order: 22,
              compliance_section_group_id: 'csg_mnjg81nrtfgsphp4',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 6,
              },
            },
          ],
        },
        {
          sectionGroupId: 'csg_xcv2gzlmrrucrzr5',
          sections: [
            {
              id: 'cs_s6j2ed6vzawao8pd',
              key: 'GHG',
              title: 'GHG Emissions & Climate',
              metadata: null,
              order: 3,
              compliance_section_group_id: 'csg_xcv2gzlmrrucrzr5',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 20,
              },
            },
          ],
        },
        {
          sectionGroupId: 'csg_gnawsv7bv67xumws',
          sections: [
            {
              id: 'cs_hy7ogimm4bfnzvy9',
              key: 'PRD',
              title: 'Product Care, Repair, Reuse & End-of-life',
              metadata: null,
              order: 21,
              compliance_section_group_id: 'csg_gnawsv7bv67xumws',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 7,
              },
            },
            {
              id: 'cs_iwm8sg46j8thawb3',
              key: 'PSA',
              title: 'Product Sustainability & Preferred Attributes',
              metadata: null,
              order: 18,
              compliance_section_group_id: 'csg_gnawsv7bv67xumws',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 3,
              },
            },
            {
              id: 'cs_uooqzhc9ibc5uaaw',
              key: 'APK',
              title: 'Packaging - Apparel',
              metadata: null,
              order: 20,
              compliance_section_group_id: 'csg_gnawsv7bv67xumws',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 6,
              },
            },
            {
              id: 'cs_zjxjwkrlqbkkl7e6',
              key: 'PKG',
              title: 'Packaging - General',
              metadata: null,
              order: 19,
              compliance_section_group_id: 'csg_gnawsv7bv67xumws',
              compliance_definition_name: 'rei_pia_2024',
              _count: {
                compliance_questions: 4,
              },
            },
          ],
        },
      ],
    },
  ];
  // find mock data by compliance_definition_name and compliance_section_group_id
  const complianceData = find(mockData, item => item.name === name);
  if (!complianceData) return [];
  const sectionGroupData = find(complianceData.section_groups, group => group.sectionGroupId === sectionGroupId);
  if (!sectionGroupData) return [];
  return sectionGroupData.sections;
};

export const getQuestionList = (args: any): MQTTComplianceManagerPayloadComplianceQuestionList | undefined => {
  const name = get(args, 'name', '');
  const sectionGroupId = get(args, 'sectionGroupId', '');
  const sectionId = get(args, 'sectionId', '');
  const mockData = [
    {
      name: 'rei_pia_2024',
      section_groups: [
        {
          sectionGroupId: 'csg_ual97c2pos346hkf',
          sections: [
            {
              id: 'cs_cr9ud1djx1h7xrem',
              key: 'WL',
              title: 'Wool',
              questions: [
                {
                  id: 'cq_e3ak6b2a61oee4a5',
                  prompt: 'Is the policy/target publicly available?',
                  order: 65,
                  key: 'WL-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_yz224cusx4398vh7',
                  prompt:
                    'The REI Product Impact Standards include the expectation that all products supplied to REI that contain virgin wool meet standards that safeguard the well-being of sheep in the wool supply chain and prohibit mulesing.\n\nDoes your brand have a formal policy/target in place regarding animal welfare in your wool supply chain?',
                  order: 64,
                  key: 'WL-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_fkhppv9zp5yk4qg0',
              key: 'FR',
              title: 'Flame Retardant (FR) Chemicals',
              questions: [
                {
                  id: 'cq_khbzin0ocml803do',
                  prompt:
                    'The REI Product Impact Standards include the expectation that all camping shelters supplied to REI be free of prohibited flame retardant (FR) chemicals.\n(See REI’s Product Impact Standards for a list of prohibited FR chemicals.)\n\nDoes your brand have a formal policy/target in place regarding the use of FR chemicals in your products?',
                  order: 59,
                  key: 'FR-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_lcon919kbpstqfd2',
                  prompt: 'Does your brand have plans to transition away from the use of all flame retardants in your tents?',
                  order: 61,
                  key: 'FR-3',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_mv2pd426jphtxdfq',
                  prompt: 'Is the policy/target publicly available?',
                  order: 60,
                  key: 'FR-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_kvyvslvd8k9b6u9l',
              key: 'CHEM',
              title: 'Restricted Substances List & Chemicals Management',
              questions: [
                {
                  id: 'cq_d2cmihcr4mwpn2sa',
                  prompt: 'Please specify which third-party RSL(s).',
                  order: 30,
                  key: 'CHEM-3A',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_jba9yyibiexy6zx7',
                  prompt: 'Is your brand’s RSL publicly available?',
                  order: 31,
                  key: 'CHEM-4',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_pvz2w191snt5jwu4',
                  prompt: 'Does your brand have a means of verifying that products you supply to REI comply with your RSL?',
                  order: 27,
                  key: 'CHEM-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_v8379scq7pncl3d5',
                  prompt: 'Is your RSL aligned to an internationally recognized third-party RSL?',
                  order: 29,
                  key: 'CHEM-3',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_wu2kksbvijpxmyc3',
                  prompt:
                    'As part of the REI Product Impact Standards, REI expects each brand partner to have in place a Restricted Substances List (RSL) that specifies which substances are banned or restricted in products and that meets or exceeds all applicable regulatory requirements.\n\nDoes your brand have an RSL in place for the products you supply to REI?',
                  order: 26,
                  key: 'CHEM-0',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_y5ar15bfkrud9ysx',
                  prompt: 'Please indicate whether your brand’s chemicals management program consists of the following components that aid in verifying compliance with your RSL.',
                  order: 28,
                  key: 'CHEM-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_uzcancxkpelymuv9',
              key: 'DWN',
              title: 'Down',
              questions: [
                {
                  id: 'cq_jywf6nk3jayowvph',
                  prompt: 'Is the policy/target publicly available?',
                  order: 63,
                  key: 'DWN-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_qbvdagm4mtmyxh1n',
                  prompt:
                    'The REI Product Impact Standards include the expectation that all products supplied to REI that contain virgin down meet standards that safeguard the well-being of ducks and geese in the down supply chain and prohibit live-plucking and force-feeding.\n\nDoes your brand have a formal policy/target in place regarding animal welfare in your down supply chain?',
                  order: 62,
                  key: 'DWN-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_v4qmnk2ubja9ko3x',
              key: 'AFL',
              title: 'Animal Fur & Exotic Leather',
              questions: [
                {
                  id: 'cq_v7i1n0ubpkyas452',
                  prompt:
                    'The REI Product Impact Standards include the expectation that products supplied to REI do not contain animal fur or exotic leather. (See REI’s Product Impact Standards for a definition of exotic leather.)\n\nDoes your brand have a formal policy/target in place regarding the use of animal fur and exotic leather in your products?',
                  order: 66,
                  key: 'AFL-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_vyepxssb74qh1gxa',
                  prompt: 'Is the policy/target publicly available?',
                  order: 67,
                  key: 'AFL-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_zt32iw2npcxotdvl',
                  prompt:
                    'Does your brand have a formal policy/target in place regarding the geographic origin of the leather used in your products (e.g., avoiding sourcing from regions undergoing deforestation, etc.)?',
                  order: 68,
                  key: 'AFL-3',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_w3a3maz46vkbwto0',
              key: 'BPA',
              title: 'Bisphenol A',
              questions: [
                {
                  id: 'cq_lgsp51ovp1r7cp4i',
                  prompt: 'Is the policy/target publicly available?',
                  order: 55,
                  key: 'BPA-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_xnq4kaxdiu70buj8',
                  prompt:
                    'The REI Product Impact Standards include the expectation that products supplied to REI that are meant to come in direct contact with food or liquids for human consumption be free of Bisphenol A (BPA).\n\nDoes your brand have a formal policy/target in place regarding the use of BPA in your products?',
                  order: 54,
                  key: 'BPA-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_w3yijeqzqzh5z4lw',
              key: 'SUN',
              title: 'Sunscreen Ingredients',
              questions: [
                {
                  id: 'cq_qqqbzm6mlwa8t7b2',
                  prompt: 'Does your brand have a formal policy/target in place that includes avoiding the use of other active sunscreen ingredients?',
                  order: 58,
                  key: 'SUN-3',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_vsra7uutc0t8pert',
                  prompt:
                    'The REI Product Impact Standards include the expectation that sunscreens and formulated sun-protection products supplied to REI be free of oxybenzone and contain only active ingredients that are generally recognized as safe and effective.\n\nDoes your brand have a formal policy/target in place regarding the use of oxybenzone in your products?',
                  order: 56,
                  key: 'SUN-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_yrn1kkvqwzw0a473',
                  prompt: 'Is the policy/target publicly available?',
                  order: 57,
                  key: 'SUN-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_xpfz8pcnz5l3q7hn',
              key: 'PFAS',
              title: 'Per- and Polyfluoroalkyl Substances',
              questions: [
                {
                  id: 'cq_dsgcgwyjewjzu1u9',
                  prompt:
                    'The REI Product Impact Standards include the existing expectation that all apparel, footwear, packs, sleeping bags or tents supplied to REI be free of long-chain PFAS and that all ski wax and gear & clothing treatments supplied to REI be free of long-chain and short-chain PFAS.\n\nDoes your brand have a formal policy/target in place regarding the presence of PFAS in your products?',
                  order: 52,
                  key: 'PFAS-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_wken6vurxtj1klvl',
                  prompt: 'Is the policy/target publicly available?',
                  order: 53,
                  key: 'PFAS-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
          ],
        },
        {
          sectionGroupId: 'csg_u52xp76tclba5djc',
          sections: [
            {
              id: 'cs_g5prbr04liwq2iy6',
              key: 'INC',
              title: 'Diversity & Inclusion: General',
              questions: [
                {
                  id: 'cq_f8hasmaft6xxu0uw',
                  prompt: 'Does your policy explicitly prohibit discrimination based on both sexual orientation and gender identity?',
                  order: 82,
                  key: 'INC-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_fl5vwy0ods15a0tb',
                  prompt:
                    'This subset of questions is related to diversity, equity and inclusion practices at your organization, not limited to the product space. As REI seeks to progress a more inclusive outdoor industry, we are hoping to understand where brands are at.\n\nDoes your brand have a policy/policies in place regarding nondiscrimination as related to employment, customer service, grant-making or other areas?',
                  order: 81,
                  key: 'INC-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_gataayg43kzordz5',
                  prompt: 'Please select one the following to describe the reach of your nondiscrimination policy.',
                  order: 83,
                  key: 'INC-3',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_l8e7di1bysiv7lss',
                  prompt: 'Does your brand have in place a policy or practice for pay equity across gender and race?',
                  order: 85,
                  key: 'INC-5',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_qhoomtjw9ef00ao5',
                  prompt: 'Does your brand have in place a policy for healthcare explicitly inclusive of the LGBTQ+ community?',
                  order: 86,
                  key: 'INC-6',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_u21jqrm4u6l2forz',
                  prompt: "Does your brand have/plan to create product that is designed beyond the gender binary (i.e. not women or men's only)?",
                  order: 84,
                  key: 'INC-4',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_m85htg8kkj8psfbc',
              key: 'MKT',
              title: 'Diversity & Inclusion: Marketing Diversity',
              questions: [
                {
                  id: 'cq_hpc48itscepqkdg6',
                  prompt: 'What strategies is your brand currently using as part of its guidelines?',
                  order: 72,
                  key: 'MKT-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_luyd6oh0w1d7leqj',
                  prompt: 'Which dimensions of diversity or other topics do your guidelines address?',
                  order: 73,
                  key: 'MKT-3',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_v7b6hyqg3gfjs489',
                  prompt:
                    'The REI Product Impact Standards include the expectation that each brand partner has in place guidelines for marketing assets, photo casting and production that ensure diverse and inclusive representation across race, age, gender identity/expression, body size and disability. Content supplied to REI by influencers and affiliate media, as well as photography, marketing copy, and other content, shall reflect the same inclusive representation.\n\nWhich option below best describes your brand’s status, as of Spring 2023 product lines and marketing, in addressing diverse and inclusive representation in its marketing and photo casting?',
                  order: 71,
                  key: 'MKT-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_mlwf1rptdl1nf0f5',
              key: 'APP',
              title: 'Diversity & Inclusion: Cultural Appropriation',
              questions: [
                {
                  id: 'cq_ho1blgggzk8gat67',
                  prompt:
                    'As part of the REI Product Impact Standards, REI has established several expectations related to diversity and inclusion that we would like brand partners to implement. The following questions are intended to understand brand partners’ current state in implementing these practices.\n\nThe REI Product Impact Standards include the expectation that each brand partner has in place creative controls to prevent cultural appropriation: plagiarism, theft and/or inappropriate use of designs, patterns, forms, materials, words/names, etc. that are culturally meaningful to and/or originated from underrepresented communities. These creative controls should ensure that the development of products, promotions, and marketing used during annual cultural moments (e.g., Pride, Black History Month etc.) is shaped by members of the represented communities.\n\nWhich option below best describes how your brand is actively mitigating cultural appropriation, as of Spring 2024 product lines and marketing?',
                  order: 69,
                  key: 'APP-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_pu6sv6tnp6yl1n2m',
                  prompt: 'Which creative controls is your brand currently using to prevent cultural appropriation?',
                  order: 70,
                  key: 'APP-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_oqro7y64jpwjauar',
              key: 'COL',
              title: 'Diversity & Inclusion: Inclusive Colorways',
              questions: [
                {
                  id: 'cq_f3dxwn3f574wygse',
                  prompt:
                    'The REI Product Impact Standards include the expectation that all wearable products supplied to REI be available in colorways appropriate for a range of skin tones/complexions; and that product marketed as ‘Nude’ including those with embellishments and/or linings intended to give the impression of bare skin or to mimic skin tone, be available in a range of tones.\n\nWhich of the following describes the active creative controls your brand has in place to ensure colorways of wearable products are appropriate for a variety of skin tones/complexions?',
                  order: 76,
                  key: 'COL-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_ixp28a5byvxdahil',
                  prompt: 'Which of the following strategies is your brand currently using to address inclusion in its color offering?',
                  order: 77,
                  key: 'COL-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_pjmqyrrfzbtqvbi7',
              key: 'COP',
              title: 'Diversity & Inclusion: Inclusive Copy',
              questions: [
                {
                  id: 'cq_dbgc6e8e6tjff69o',
                  prompt: 'Which of the following policies or creative controls do you utilize as it relates to inclusive product copy?',
                  order: 75,
                  key: 'COP-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_eymywin27r7sql7t',
                  prompt:
                    'The REI Product Impact Standards include the expectation that each brand partner has in place creative controls to prevent the use of language in naming conventions (as applied to product, collection, color, or design); product information; marketing assets, etc., that negatively impact underrepresented groups (e.g., by reinforcing stereotypes, utilizing slurs, coopting cultural language, etc.).\n\nDoes your brand currently have in place policies or creative controls related to inclusive product copy?',
                  order: 74,
                  key: 'COP-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_r8wflfvf7o7tfm2q',
              key: 'ISS',
              title: 'Diversity & Inclusion: Inclusive Sizing',
              questions: [
                {
                  id: 'cq_mc4fi040gdht0ujm',
                  prompt:
                    'The REI Product Impact Standards has an expectation that all brand partners who sell wearable products offered in a variety of sizes maintain the same price within a style regardless of size. \n\nDoes your brand currently maintain the same price across wearable products offered in a variety of sizes regardless of size?',
                  order: 79,
                  key: 'ISS-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_roa9rjksxxga0fg3',
                  prompt:
                    'The REI Product Impact Standard has an expectation that each brand partner that sells wearable products offered in a variety of sizes to provide REI at least one sample size outside the standard size range for marketing photography. \n\nAs a standard practice, does your brand currently send REI at least one sample size outside the standard size range for marketing photography of wearable products?',
                  order: 78,
                  key: 'ISS-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_v7aqyq1r17ndfh2i',
              key: 'DHT',
              title: 'Diversity & Inclusion: Diverse Hair Type Inclusion',
              questions: [
                {
                  id: 'cq_qvh3x3qxik3ov5cf',
                  prompt:
                    'The REI Product Impact Standards has an expectation that each brand partner that produces headwear (helmets, hats, headbands, hoods, balaclavas, hijab, etc.) to have in place guidelines for ensuring an inclusive assortment for a variety of hair types, including higher-volume and textured hair.\n\nWhich of the below options best represents how your brand is approaching the Diverse Hair Type Inclusion expectation?',
                  order: 80,
                  key: 'DHT-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
          ],
        },
        {
          sectionGroupId: 'csg_mnjg81nrtfgsphp4',
          sections: [
            {
              id: 'cs_a6ggbg5yueu9h3x9',
              key: 'MFG',
              title: 'Manufacturing Code of Conduct & Responsible Sourcing',
              questions: [],
            },
            {
              id: 'cs_pfcuqh8485r84svr',
              key: 'GEN',
              title: 'Brand Information',
              questions: [],
            },
            {
              id: 'cs_pj88et1zsce8ubf1',
              key: 'CRP',
              title: 'Core Practices',
              questions: [],
            },
          ],
        },
        {
          sectionGroupId: 'csg_xcv2gzlmrrucrzr5',
          sections: [
            {
              id: 'cs_s6j2ed6vzawao8pd',
              key: 'GHG',
              title: 'GHG Emissions & Climate',
              questions: [
                {
                  id: 'cq_acl5xoqubd5xrhrt',
                  prompt: "Has your brand's carbon footprint been verified by an independent third-party?",
                  order: 35,
                  key: 'GHG-4',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_brmw2dehxwk63u3l',
                  prompt: 'Please indicate which components of your operations were included in your carbon footprint.',
                  order: 34,
                  key: 'GHG-3',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_cz4lbnce3paca1we',
                  prompt: 'Does your brand generate and/or purchase carbon credits to “offset” all or a portion of your carbon emissions?',
                  order: 49,
                  key: 'GHG-11',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_d1lndzseoyy3tbdf',
                  prompt:
                    'Is your brand certified to a third-party standard that validates that you’ve purchased carbon credits sufficient to “offset” the relevant components of your carbon footprint (e.g., Climate Neutral Certified)?',
                  order: 51,
                  key: 'GHG-13',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_ex4isjfnbrsm3v0j',
                  prompt: 'Has your brand set a quantitative target(s) to reduce your carbon emissions?',
                  order: 39,
                  key: 'GHG-7',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_fa8x39qqhz262q4p',
                  prompt: 'Has your emission reduction target(s) been approved by the Science Based Targets Initiative (SBTi) or an equivalent framework?',
                  order: 45,
                  key: 'GHG-8',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_galura03nwpd08fd',
                  prompt: 'Please indicate whether your brand uses spend or material-based emissions factors to calculate your product carbon emissions.',
                  order: 38,
                  key: 'GHG-6A',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_horxl61g5usvn4wg',
                  prompt:
                    'Did your brand’s carbon emissions over the previous year represent a measurable reduction in emissions intensity (i.e., carbon emissions per unit of product or dollar of revenue) relative to the prior year or a previous baseline year?',
                  order: 48,
                  key: 'GHG-10',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_iij4l0x9ndl166w7',
                  prompt: 'Has your brand established an emissions reduction action plan or roadmap that guides your efforts to achieve your reduction targets?',
                  order: 46,
                  key: 'GHG-9',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_k83xt4ur258x0w8y',
                  prompt: 'Was your carbon footprint calculated using an internationally recognized greenhouse gas accounting standard (e.g., the GHG Protocol)?',
                  order: 33,
                  key: 'GHG-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_m21lsu4gy6xq03dg',
                  prompt:
                    'Please tell us about your quantitative Scope 3 reduction targets.\n\nWhat percent reduction are you aiming to achieve from your baseline year to your target year?',
                  order: 41,
                  key: 'GHG-7B:1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_mbpfnpei8sve11rd',
                  prompt: 'Does your brand calculate the carbon emissions from individual products you sell?',
                  order: 37,
                  key: 'GHG-6',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_o4683o1czv7ffz34',
                  prompt: 'What are the primary components of your emissions reduction action plan?',
                  order: 47,
                  key: 'GHG-9A',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_oqj3urd5yii0unrx',
                  prompt: 'Please tell us about your quantitative Scope 3 reduction targets.\n\nWhat year are you using as your baseline year?',
                  order: 42,
                  key: 'GHG-7B:2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_p9h7jtmfo6on473m',
                  prompt: 'Which components of your carbon footprint are covered by your quantitative reduction target?',
                  order: 40,
                  key: 'GHG-7A',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_qmd029cn7dpcy8nw',
                  prompt: 'Please indicate whether the carbon credits you generate and/or purchase account for and include the following components of your carbon footprint.',
                  order: 50,
                  key: 'GHG-12',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_t4drzwwh97yrcm7s',
                  prompt: 'Please tell us about your quantitative Scope 3 reduction targets.\n\nWhat year are you using as your target year?',
                  order: 43,
                  key: 'GHG-7B:3',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_v7k1dazhry3ishnu',
                  prompt:
                    'Please select one of the following to indicate if your target is for absolute emissions reduction (i.e., total carbon emissions) or reduction in emissions intensity (i.e., carbon emissions per unit of product or dollar of revenue):',
                  order: 44,
                  key: 'GHG-7C',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_vjo5lce3h7nyurfy',
                  prompt: 'Does your brand report its carbon footprint publicly?',
                  order: 36,
                  key: 'GHG-5',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_xs4bvfkrromfc20u',
                  prompt:
                    'As part of the REI Product Impact Standards, REI expects each brand partner to measure their annual greenhouse gas (GHG) emissions, set a reduction target, and implement an action plan for reducing their emissions. The following section focuses on the steps your brand is taking to address your contribution to climate change.\n\nHas your brand measured its carbon footprint this year or within the last calendar year?',
                  order: 32,
                  key: 'GHG-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
          ],
        },
        {
          sectionGroupId: 'csg_gnawsv7bv67xumws',
          sections: [
            {
              id: 'cs_hy7ogimm4bfnzvy9',
              key: 'PRD',
              title: 'Product Care, Repair, Reuse & End-of-life',
              questions: [
                {
                  id: 'cq_fvsbqaiye12ovk1i',
                  prompt: 'Does your brand provide customers with guidance for how to use and care for your product in an environmentally responsible manner?',
                  order: 100,
                  key: 'PRD-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_jsfz7wpqo4madvw0',
                  prompt: 'Does your brand offer a lifetime warranty for products?',
                  order: 101,
                  key: 'PRD-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_k0yj0tj16u06m5mj',
                  prompt: 'Are the repairs conducted in-house or through a third-party?',
                  order: 103,
                  key: 'PRD-4',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_qf8p0hurvwx9b6ry',
                  prompt: 'Does your brand offer solutions for your customers to donate and/or recycle products at end-of-life?',
                  order: 106,
                  key: 'PRD-7',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_u5lxsshxa4z88sgn',
                  prompt: 'Does your brand provide product repair services to your customers?',
                  order: 102,
                  key: 'PRD-3',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_xl9iogy4kp764qyf',
                  prompt: 'Does your brand sell used products?',
                  order: 104,
                  key: 'PRD-5',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_yga8el7bq1j2roji',
                  prompt: 'Does your brand rent or lease products to your customers?',
                  order: 105,
                  key: 'PRD-6',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_iwm8sg46j8thawb3',
              key: 'PSA',
              title: 'Product Sustainability & Preferred Attributes',
              questions: [
                {
                  id: 'cq_d5ll8h676h6707xp',
                  prompt: "Please select which of REI's preferred sustainability attributes your brand has policies or targets in place for (if any)",
                  order: 88,
                  key: 'PSA-2:1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_h9y6wqh1se68lnr2',
                  prompt: 'For the ones you have policies or targets in place for, please select ones where the policies or targets are publicly available.',
                  order: 89,
                  key: 'PSA-2:2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_ppu9hzo3bafupmc6',
                  prompt: 'Does your brand utilize a formal methodology or tool to measure the sustainability of your materials and/or finished products?',
                  order: 87,
                  key: 'PSA-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_uooqzhc9ibc5uaaw',
              key: 'APK',
              title: 'Packaging - Apparel',
              questions: [
                {
                  id: 'cq_d7yrh6borz2oyvmk',
                  prompt:
                    'REI’s Vendor Guide indicates that brands shipping non-white apparel items to REI should do so without individual polybags. Brands will be charged a $.01/unit polybag recycling fee for apparel items arriving in individual polybags at an REI receiving location. Please refer to REI’s Vendor Guide (available on the REI Partners Site) for more information.\n\nApproximately what percentage of the apparel product units your brand shipped to REI during the past calendar year were packaged in individual polybags?',
                  order: 94,
                  key: 'APK-1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_n1fry37w1irxojkx',
                  prompt:
                    'As of the Spring 2024 product season, have you implemented as your standard practice the shipment of non-white apparel products to REI without the use of individual polybags?',
                  order: 98,
                  key: 'APK-5',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_o8hr1vgm4q4zzwxe',
                  prompt:
                    'Approximately what percentage of the apparel product units your brand shipped to REI during the past calendar year were packaged in a master polybag containing all units in each carton?',
                  order: 95,
                  key: 'APK-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_p932mlspe841elr7',
                  prompt: 'If you ship apparel items to REI without individual polybags, how are they packaged?',
                  order: 96,
                  key: 'APK-3',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_pemwl83szaok5evo',
                  prompt: 'Approximately what percentage of the apparel product units that you ship to REI during the coming year will be packaged in individual polybags?',
                  order: 97,
                  key: 'APK-4',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_rvdeuwgjjno3mc6k',
                  prompt:
                    'If your brand is unable to ship non-white apparel items to REI without the use of individual polybags, please describe the key factors that prevent you from doing so.',
                  order: 99,
                  key: 'APK-6',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
            {
              id: 'cs_zjxjwkrlqbkkl7e6',
              key: 'PKG',
              title: 'Packaging - General',
              questions: [
                {
                  id: 'cq_d8yncydlvqv12fnh',
                  prompt: 'Has your brand been able to phase out the use of single-use plastics across any noteworthy areas of primary or secondary product packaging?',
                  order: 92,
                  key: 'PKG-2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_eh4nivkqk4p6dip6',
                  prompt: 'Please indicate whether your brand has formal policies/targets in place regarding the use of more sustainable product packaging.',
                  order: 90,
                  key: 'PKG-1:1',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_fsga7wa1g0yio647',
                  prompt: 'Are there other best sustainability practices for primary product packaging that you have in place that you’d like to share with REI?',
                  order: 93,
                  key: 'PKG-3',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
                {
                  id: 'cq_lrpqk7q5e9uzlh5q',
                  prompt: 'For the ones you have policies or targets in place for, please select ones where the policies or targets are publicly available.',
                  order: 91,
                  key: 'PKG-1:2',
                  organization_id: 'org_VWv3Al9pLEI4CaOH',
                  not_started: true,
                  ai_answered: false,
                  user_answered: false,
                  bookmarked: false,
                },
              ],
            },
          ],
        },
      ],
    },
  ];

  // get the questions by compliance_definition_name, compliance_section_group_id, and section_id
  const complianceData = find(mockData, item => item.name === name);
  if (!complianceData) return undefined;
  const sectionGroupData = find(complianceData.section_groups, group => group.sectionGroupId === sectionGroupId);
  if (!sectionGroupData) return undefined;
  const sectionData = find(sectionGroupData.sections, section => section.id === sectionId);
  if (!sectionData) return undefined;
  return {
    compliance_questions: sectionData.questions,
    counts: {
      total: sectionData.questions.length,
      not_started: sectionData.questions.filter(question => question.not_started).length,
      ai_answered: sectionData.questions.filter(question => question.ai_answered).length,
      user_answered: sectionData.questions.filter(question => question.user_answered).length,
      bookmarked: sectionData.questions.filter(question => question.bookmarked).length,
    },
  };
};

export const getComplianceSectionProgressBarQuestionsMock = () => {
  return [
    {
      id: 'cq_d7yrh6borz2oyvmk',
      prompt:
        'REI’s Vendor Guide indicates that brands shipping non-white apparel items to REI should do so without individual polybags. Brands will be charged a $.01/unit polybag recycling fee for apparel items arriving in individual polybags at an REI receiving location. Please refer to REI’s Vendor Guide (available on the REI Partners Site) for more information.\n\nApproximately what percentage of the apparel product units your brand shipped to REI during the past calendar year were packaged in individual polybags?',
      order: 94,
      key: 'APK-1',
      organization_id: 'org_VWv3Al9pLEI4CaOH',
      not_started: true,
      ai_answered: false,
      user_answered: false,
      bookmarked: false,
    },
    {
      id: 'cq_n1fry37w1irxojkx',
      prompt:
        'As of the Spring 2024 product season, have you implemented as your standard practice the shipment of non-white apparel products to REI without the use of individual polybags?',
      order: 98,
      key: 'APK-5',
      organization_id: 'org_VWv3Al9pLEI4CaOH',
      not_started: false,
      ai_answered: true,
      user_answered: false,
      bookmarked: false,
    },
    {
      id: 'cq_o8hr1vgm4q4zzwxe',
      prompt:
        'Approximately what percentage of the apparel product units your brand shipped to REI during the past calendar year were packaged in a master polybag containing all units in each carton?',
      order: 95,
      key: 'APK-2',
      organization_id: 'org_VWv3Al9pLEI4CaOH',
      not_started: false,
      ai_answered: false,
      user_answered: true,
      bookmarked: false,
    },
    {
      id: 'cq_p932mlspe841elr7',
      prompt: 'If you ship apparel items to REI without individual polybags, how are they packaged?',
      order: 96,
      key: 'APK-3',
      organization_id: 'org_VWv3Al9pLEI4CaOH',
      not_started: false,
      ai_answered: false,
      user_answered: true,
      bookmarked: false,
    },
    {
      id: 'cq_pemwl83szaok5evo',
      prompt: 'Approximately what percentage of the apparel product units that you ship to REI during the coming year will be packaged in individual polybags?',
      order: 97,
      key: 'APK-4',
      organization_id: 'org_VWv3Al9pLEI4CaOH',
      not_started: false,
      ai_answered: false,
      user_answered: false,
      bookmarked: true,
    },
    {
      id: 'cq_rvdeuwgjjno3mc6k',
      prompt:
        'If your brand is unable to ship non-white apparel items to REI without the use of individual polybags, please describe the key factors that prevent you from doing so.',
      order: 99,
      key: 'APK-6',
      organization_id: 'org_VWv3Al9pLEI4CaOH',
      not_started: false,
      ai_answered: false,
      user_answered: false,
      bookmarked: true,
    },
  ];
};

export const getComplianceManagerOverviewSectionsMock = () => {
  return {
    section: {
      id: 'cs_kvyvslvd8k9b6u9l',
      key: 'CHEM',
      title: 'Restricted Substances List & Chemicals Management',
      metadata: null,
      order: 2,
      compliance_section_group_id: 'csg_ual97c2pos346hkf',
      compliance_definition_name: 'rei_pia_2024',
      _count: {
        compliance_questions: 6,
      },
    },
    groupId: 'csg_ual97c2pos346hkf',
  };
};

export const getComplianceManagerOverviewSectionQuestionListMock = (args: any) => {
  return {
    counts: {
      total: 6,
      not_started: 6,
      ai_answered: 0,
      user_answered: 0,
      bookmarked: 0,
    },
    compliance_questions: [
      {
        id: 'cq_d2cmihcr4mwpn2sa',
        prompt: 'Please specify which third-party RSL(s).',
        order: 30,
        key: 'CHEM-3A',
        organization_id: 'org_VWv3Al9pLEI4CaOH',
        not_started: true,
        ai_answered: false,
        user_answered: false,
        bookmarked: false,
      },
      {
        id: 'cq_jba9yyibiexy6zx7',
        prompt: 'Is your brand’s RSL publicly available?',
        order: 31,
        key: 'CHEM-4',
        organization_id: 'org_VWv3Al9pLEI4CaOH',
        not_started: true,
        ai_answered: false,
        user_answered: false,
        bookmarked: false,
      },
      {
        id: 'cq_pvz2w191snt5jwu4',
        prompt: 'Does your brand have a means of verifying that products you supply to REI comply with your RSL?',
        order: 27,
        key: 'CHEM-1',
        organization_id: 'org_VWv3Al9pLEI4CaOH',
        not_started: true,
        ai_answered: false,
        user_answered: false,
        bookmarked: false,
      },
      {
        id: 'cq_v8379scq7pncl3d5',
        prompt: 'Is your RSL aligned to an internationally recognized third-party RSL?',
        order: 29,
        key: 'CHEM-3',
        organization_id: 'org_VWv3Al9pLEI4CaOH',
        not_started: true,
        ai_answered: false,
        user_answered: false,
        bookmarked: false,
      },
      {
        id: 'cq_wu2kksbvijpxmyc3',
        prompt:
          'As part of the REI Product Impact Standards, REI expects each brand partner to have in place a Restricted Substances List (RSL) that specifies which substances are banned or restricted in products and that meets or exceeds all applicable regulatory requirements.\n\nDoes your brand have an RSL in place for the products you supply to REI?',
        order: 26,
        key: 'CHEM-0',
        organization_id: 'org_VWv3Al9pLEI4CaOH',
        not_started: true,
        ai_answered: false,
        user_answered: false,
        bookmarked: false,
      },
      {
        id: 'cq_y5ar15bfkrud9ysx',
        prompt: 'Please indicate whether your brand’s chemicals management program consists of the following components that aid in verifying compliance with your RSL.',
        order: 28,
        key: 'CHEM-2',
        organization_id: 'org_VWv3Al9pLEI4CaOH',
        not_started: true,
        ai_answered: false,
        user_answered: false,
        bookmarked: false,
      },
    ],
  };
};
