export const mock = {
  title: 'REI Product Impact Standards',
  rules: [
    "$lookup(sections.MFG.follow_up, 'MFG-1').ai_answered = true ? $lookup(sections, 'PKG') : {}",
    "$lookup(sections.MFG.follow_up, 'GHG-1').ai_answered = true ? $lookup(sections.MFG.follow_up, 'GHG-2') : {}",
    "$lookup(sections.MFG.follow_up, 'GHG-1').ai_answered = true ? $lookup(sections.MFG.follow_up, 'GHG-3') : {}",
    "$lookup(sections.MFG.follow_up, 'GHG-1').ai_answered = true ? $lookup(sections.MFG.follow_up, 'GHG-4') : {}",
  ],
  sections: {
    GEN: {
      title: 'General',
      prompt: 'Please complete the REI Product Impact Standards survey to the best of your ability. If you have any questions, please contact your REI Sustainability Manager.',
      component: null,
      follow_up: {
        'GEN-8': {
          idx: 0,
          prompt:
            'Please indicate if your brand has supplied to REI in the past 12 months, or anticipates supplying to REI in the next 12 months, products that fall into any of the following categories.',
          value: ['Apparel', 'Cookware', 'Footwear', 'Headwear'],
          options: [
            'Apparel',
            'Accessories (textile-based)',
            'Cookware',
            'Footwear',
            'Headwear',
            'Other textile products',
            'Packs',
            'Products that contain down',
            'Products that contain leather',
            'Products that contain wool',
            'Ski wax',
            'Sleeping bags',
            'Sunscreens or other formulated sun-protection products',
            'Tents',
            'Treatments for gear and clothing',
            'Water bottles, food containers, dinnerware or utensils',
            'None of the above',
          ],
          tooltip: 'Select all that apply.',
          component: 'multi_select',
          placeholder: '',
        },
      },
    },
    MFG: {
      title: 'Manufacturing Code of Conduct',
      prompt: '',
      component: null,
      follow_up: {
        'MFG-1': {
          idx: 0,
          prompt: 'Does your brand have in place a code of conduct for factories that manufacture the products you supply to REI?',
          options: [],
          tooltip: '',
          component: 'yes_no',
          placeholder: '',
          value: false,
          additional_context: {
            prompt: "Please describe how your brand plans to align with REI's expectation in this area.",
            operator: '==',
            component: 'textarea',
            comparison: false,
            placeholder: '',
          },
        },
        'MFG-2': {
          idx: 1,
          prompt: 'Please indicate which of the following topics are included in your manufacturing code of conduct.',
          options: [
            'Transparency',
            'Non-discrimination',
            'Harassment and Abuse',
            'Recruitment and Hiring',
            'Freedom of Association & Collective Bargaining',
            'Hours of Work',
            'Compensation',
            'Health & Safety',
            'Environment',
            'Community',
            'Other',
          ],
          tooltip: 'Select all that apply.',
          component: 'multi_select',
          placeholder: '',
          depends_on: 'MFG-1',
          dependency_function: '$lookup(sections.$s.follow_up, $q).value = true',
          additional_context: {
            prompt: 'Please enter other topics included in your code of conduct. If entering multiple, separate using commas',
            operator: '==',
            component: 'textarea',
            comparison: ['Other'],
            placeholder: '',
          },
        },
        'MFG-3': {
          idx: 2,
          prompt: 'To which tiers of your supply chain has your code of conduct been formally communicated and implemented?',
          options: [
            'Tier 1 (finished product manufacturers)',
            'Tier 2 (finished material/subcomponent manufacturers)',
            'Tier 3 (raw material processors)',
            'Tier 4 (raw material suppliers)',
          ],
          depends_on: 'MFG-1',
          dependency_function: '$lookup(sections.$s.follow_up, $q).value = true',
          tooltip: 'Select all that apply.',
          component: 'multi_select',
          placeholder: '',
        },
        'MFG-4': {
          idx: 3,
          prompt: 'Is your brand’s manufacturing code of conduct publicly available?',
          options: [],
          tooltip: '',
          component: 'yes_no',
          placeholder: '',
          depends_on: 'MFG-1',
          dependency_function: '$lookup(sections.$s.follow_up, $q).value = true',
          additional_context: {
            prompt: 'Provide the hyperlink',
            operator: '==',
            component: 'textarea',
            comparison: true,
            placeholder: '',
          },
        },
      },
      image_url:
        'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1587&q=80',
      category_idx: 0,
      category_description:
        'As part of the REI Product Impact Standards, REI expects each brand partner to have in place a code of conduct that outlines the social and environmental standards to be upheld within their supply chain.',
    },
    GHG: {
      title: 'Greenhouse Gas Emissions & Climate',
      prompt: '',
      component: null,
      follow_up: {
        'GHG-1': {
          idx: 0,
          prompt: 'Has your brand measured its carbon footprint this year or within the last calendar year?',
          options: [],
          tooltip: 'Note: The term carbon is used here as a generally accepted shorthand for greenhouse gas.',
          component: 'yes_no',
          placeholder: '',
        },
        'GHG-2': {
          idx: 1,
          prompt: 'Was your carbon footprint calculated using an internationally recognized greenhouse gas accounting standard (e.g., the GHG Protocol)?',
          options: ['Yes, using the GHG Protocol', 'Yes, using another GHG accounting standard (please indicate below)', 'No'],
          tooltip: 'Note: The term carbon is used here as a generally accepted shorthand for greenhouse gas.',
          based_on: 'GHG-1',
          component: 'select',
          placeholder: '',
          additional_context: {
            prompt: 'Please indicate which standard(s) you used. (Note: If entering multiple, separate using commas.)',
            operator: '==',
            component: 'textarea',
            comparison: 'Yes, using another GHG accounting standard (please indicate below)',
            placeholder: '',
          },
        },
        'GHG-3': {
          idx: 2,
          prompt: 'Was your carbon footprint calculated using an internationally recognized greenhouse gas accounting standard (e.g., the GHG Protocol)?',
          options: [
            'Scope 1: Direct emissions from company vehicles & facilities',
            'Scope 2: Indirect emission from purchased electricity, steam, heating & cooling for own use',
            'Scope 3: Indirect emissions from purchased goods and services (i.e., Category 1)',
            'Scope 3: Indirect emissions from all other upstream and downstream sources (i.e., Categories 2-15)',
          ],
          tooltip: '',
          component: 'multi_select',
          placeholder: '',
        },
        'GHG-4': {
          idx: 3,
          prompt: "Has your brand 's carbon footprint been verified by an independent third-party?",
          options: [],
          tooltip: '',
          component: 'yes_no',
          placeholder: '',
          additional_context: {
            prompt: 'Please provide the hyperlink to the verification document.',
            operator: '==',
            component: 'textarea',
            comparison: true,
            placeholder: '',
          },
        },
        'GHG-5': {
          idx: 4,
          prompt: 'Does your brand report its carbon footprint publicly?',
          options: [],
          tooltip: '',
          component: 'yes_no',
          placeholder: '',
          additional_context: {
            prompt: 'Please provide the hyperlink to your most recent public report.',
            operator: '==',
            component: 'textarea',
            comparison: true,
            placeholder: '',
          },
        },
        'GHG-6': {
          idx: 5,
          prompt: 'Does your brand calculate the carbon emissions from individual products you sell?',
          options: [
            'Yes, we calculate the carbon emissions from every product we sell, including those we sell to REI.',
            'Yes, we calculate the carbon emissions from a subset of the products we sell, including those we sell to REI.',
            'Yes, we calculate the carbon emissions from a subset of the products we sell, but not including those we sell to REI.',
            'No',
          ],
          value: ['Yes, we calculate the carbon emissions from a subset of the products we sell, including those we sell to REI.'],
          tooltip: '',
          component: 'select',
          placeholder: '',
        },
        'GHG-7': {
          idx: 7,
          prompt: 'Has your brand set a quantitative target(s) to reduce your carbon emissions?',
          options: [],
          tooltip: '',
          component: 'yes_no',
          placeholder: '',
        },
        'GHG-8': {
          idx: 11,
          prompt: 'Has your emission reduction target(s) been approved by the Science Based Targets Initiative (SBTi) or an equivalent framework?',
          options: [
            'Yes, our target(s) has been approved by the SBTi',
            'No, but our target(s) is currently being evaluated by the SBTi for approval',
            'No, but we’ve aligned our target(s) with the SBTi’s guidance',
            'No, but we’ve aligned our target(s) with an equivalent framework for setting science-aligned reduction targets',
            'No',
          ],
          tooltip:
            'Note: REI considers a science-aligned target to be one that includes emissions from scopes 1, 2, and 3 and aligns with what the latest climate science indicates is necessary to limit global warming to 1.5oC above pre-industrial levels.',
          component: 'select',
          placeholder: '',
        },
        'GHG-10': {
          idx: 13,
          prompt:
            'Did your brand’s carbon emissions over the previous year represent a measurable reduction in emissions intensity (i.e., carbon emissions per unit of product or dollar of revenue) relative to the prior year or a previous baseline year?',
          options: ['Yes, a 1-25% reduction', 'Yes, a 26-50% reduction', 'Yes, a 51-75% reduction', 'Yes, a 76-99% reduction', 'Yes, a 100% reduction', 'No'],
          tooltip: '',
          component: 'select',
          placeholder: '',
        },
        'GHG-11': {
          idx: 14,
          prompt: 'Does your brand generate and/or purchase carbon credits to “offset” all or a portion of your carbon emissions?',
          options: [],
          tooltip: '',
          component: 'yes_no',
          placeholder: '',
        },
        'GHG-12': {
          idx: 15,
          prompt: 'Please indicate whether the carbon credits you generate and/or purchase account for and include the following components of your carbon footprint.',
          options: [
            'Scope 1: Direct emissions from company vehicles & facilities',
            'Scope 2: Indirect emission from purchased electricity, steam, heating & cooling for own use',
            'A portion of scope 3 emissions, but not including those from all the products you sell to REI',
            'All or a portion of scope 3 emissions, including all the products you sell to REI',
            'Other',
          ],
          tooltip: 'Select all that apply.',
          based_on: 'GHG-11',
          component: 'multi_select',
          placeholder: '',
        },
        'GHG-13': {
          idx: 16,
          prompt:
            'Is your brand certified to a third-party standard that validates that you’ve purchased carbon credits sufficient to “offset” the relevant components of your carbon footprint (e.g., Climate Neutral Certified)?',
          options: ['Yes, we’re Climate Neutral Certified', 'Yes, we’re certified to another carbon/climate neutrality standard (please describe below)', 'No'],
          tooltip: '',
          component: 'select',
          placeholder: '',
          additional_context: {
            prompt: 'If you are certified by another carbon/climate neutrality standard, please indicate which standard(s) your brand is certified to.',
            tooltip: '',
            operator: '==',
            component: 'textarea',
            comparison: 'Yes, we’re certified to another carbon/climate neutrality standard (please describe below)',
            placeholder: '',
          },
        },
        'GHG-6A': {
          idx: 6,
          prompt: 'Please indicate whether your brand uses spend or material-based emissions factors to calculate your product carbon emissions.',
          options: ['We use spend-based emissions factors', 'We use material-based emissions factors', 'Other'],
          tooltip: 'Select all that apply.',
          component: 'multi_select',
          placeholder: '',
          depends_on: 'GHG-6',
          dependency_function: '$lookup(sections.*.follow_up, $q).value = true',
          depends_on_value: ['Yes, we calculate the carbon emissions from every product we sell, including those we sell to REI.'],
          additional_context: {
            prompt: 'Please describe.',
            tooltip: 'Limit your response to 100 words or less.',
            operator: '==',
            component: 'textarea',
            comparison: 'Other',
            placeholder: '',
          },
        },
        'GHG-7A': {
          idx: 8,
          prompt: 'Which components of your carbon footprint are covered by your quantitative reduction target?',
          options: [
            'Scope 1: Direct emissions from company vehicles & facilities',
            'Scope 2: Indirect emissions from purchased electricity, steam, heating & cooling for own use',
            'Scope 3: Indirect emissions from purchased goods and services (i.e., Category 1)',
            'Scope 3: Indirect emissions from all other relevant upstream and downstream sources (i.e., Categories 2-15)',
          ],
          tooltip: 'Select all that apply.',
          component: 'multi_select',
          placeholder: '',
        },
        'GHG-7C': {
          idx: 10,
          prompt:
            'Please select one of the following to indicate if your target is for absolute emissions reduction (i.e., total carbon emissions) or reduction in emissions intensity (i.e., carbon emissions per unit of product or dollar of revenue):',
          options: ['Absolute emissions reduction', 'Reduction in emissions intensity'],
          tooltip: '',
          component: 'select',
          placeholder: '',
        },
        'GHG-9A': {
          idx: 12,
          prompt: 'What are the primary components of your emissions reduction action plan?',
          options: [
            'Use of low-carbon materials or ingredients in products',
            'Use of clean energy in product manufacturing',
            'Use of clean energy to power operations (e.g., offices, distribution centers, etc.)',
            'Minimization of materials waste in manufacturing',
            'Energy efficiency in manufacturing',
            'Use of circular business models (e.g., selling used products, renting or leasing products, product subscription, product recycling, etc.)',
            'Supporting customers in reducing emissions during product use',
            'Other (please describe)',
          ],
          tooltip: 'Select all that apply.',
          component: 'multi_select',
          placeholder: '',
          additional_context: {
            prompt: 'Please describe.',
            tooltip: '',
            operator: '==',
            component: 'textarea',
            comparison: 'Other',
            placeholder: '',
          },
        },
      },
      image_url:
        'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1587&q=80',
      category_idx: 0,
      category_description:
        'As part of the REI Product Impact Standards, REI expects each brand partner to measure their annual greenhouse gas (GHG) emissions , set a reduction target, and implement an action plan for reducing their emissions. The following section focuses on the steps your brand is taking to address your contribution to climate change.',
    },
    PFAS: {
      title: 'PFAS - STUFF',
      prompt: '',
      component: null,
      follow_up: {
        'PFAS-A1': {
          idx: 0,
          prompt: 'Does your brand have a formal policy/target in place regarding the presence of PFAS in your products?',
          depends_on: 'REI-GEN-8',
          depends_on_value: ['Apparel', 'Footwear', 'Packs', 'Ski wax', 'Sleeping bags', 'Tents', 'Treatments for gear and clothing'],
          options: [],
          tooltip: '',
          component: 'textarea',
          placeholder: '',
        },
      },
      image_url:
        'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1587&q=80',
      category_idx: 0,
      category_description: '',
    },
    APK: {
      title: 'APK - STUFF',
      prompt: '',
      component: null,
      follow_up: {
        'APK-1': {
          idx: 0,
          prompt:
            'Approximately what percentage of the apparel product units your brand shipped to REI during the past calendar year were packaged in individual polybags? (Select an option from the dropdown.)',
          options: [],
          value: '90',
          tooltip: '',
          component: 'textarea',
          placeholder: '',
        },
        'APK-2': {
          idx: 1,
          prompt:
            'AApproximately what percentage of the apparel product units your brand shipped to REI during the past calendar year were packaged in a master polybag containing all units in each carton?',
          options: [],
          tooltip: '',
          component: 'textarea',
          placeholder: '',
        },
        'APK-3': {
          idx: 2,
          prompt: 'If you ship apparel items to REI without individual polybags, how are they packaged? (Select all that apply.)',
          depends_on: 'APK-1',
          depends_on_value: '< 100',
          options: [],
          tooltip: '',
          component: 'yes_no',
          placeholder: '',
        },
        'APK-7': {
          idx: 2,
          depends_on: ['APK-1', 'APK-2'],
          depends_on_value: '>0',
          prompt:
            'Of the total number of polybags used to ship apparel products to REI during the last calendar year, please indicate approximately what percentage are made of each of the following materials:',
          options: [],
          tooltip: '',
          component: 'yes_no',
          placeholder: '',
        },
      },
    },
  },
  image_url: 'https://cold-public-assets.s3.us-east-2.amazonaws.com/splash_images/General.png',
  intro_markdown:
    'Please complete the REI Greenhouse Gas Emissions & Climate survey to the best of your ability. If you have any questions, please contact your REI Sustainability Manager.',
};
