export enum GuidPrefixes {
  'SectionGroup' = 'csg',
  'ComplianceSection' = 'cs',
  'ComplianceQuestion' = 'cq',
  'ComplianceResponse' = 'cr',
  'Organization' = 'org',
  'OrganizationFacility' = 'ofac',
  'OrganizationFile' = 'ofile',
  'OrganizationFootprint' = 'foot',
  'OrganizationCompliance' = 'oc',
  'OrganizationComplianceStatus' = 'ocs',
  'OrganizationComplianceAIResponse' = 'ocair',
  'OrganizationComplianceAiResponseFile' = 'ocairf',
  'OrganizationComplianceNote' = 'ocn',
  'OrganizationComplianceNoteLink' = 'ocnl',
  'OrganizationComplianceNoteFile' = 'ocnf',
  'ComplianceDependencyChain' = 'cdc',
  'OrganizationComplianceResponse' = 'ocr',
  'ComplianceDefinition' = 'compdef',
  'EmissionScope' = 'scope',
  'ServiceDefinitions' = 'svcdef',
  'OpenAIAssistant' = 'asst',
  'Vector' = 'vector',
  'SurveyStatus' = 'sstatus',
  'SurveyData' = 'sdata',
}
