import { PrismaClient } from '@prisma/client';
import { Cuid2Generator } from '../../src/lib/utility/cuid2-generator.service';

const prisma = new PrismaClient();
console.log('ENVIRONMENT:', process.env['NODE_ENV']);

const seeds = {
  '1': [
    'Anthracite',
    'Coking Coal',
    'Other Bituminous Coal',
    'Sub-Bituminous Coal',
    'Patent fuel',
    'Lignite or brown coal',
    'Peat Brick',
    'Peat',
    'Crude petroleum and services related to crude oil extraction, excluding surveying',
    'Natural gas',
    'Natural gas liquids',
    'Coke(fuel)',
    'Gas Coke',
    'Coal Tar',
    'Gasoline',
    'Airplane gasoline',
    'Jet Fuel',
    'Kerosene jet fuel',
    'Kerosene',
    'Diesel gas oil',
    'Heavy Fuel Oil',
    'Refinery gas',
    'Liquefied Petroleum Gases(LPG)',
    'Naphtha',
    'Petroleum coke',
    'Nuclear fuel',
    'Charcoal',
    'Biogasoline',
    'Biodiesel',
    'Other Liquid Biofuels',
    'Coke oven gas',
    'Blast Furnace Gas',
    'Oxygen Steel Furnace Gas',
    'Gas Works Gas',
    'Biogas',
    'Steam and hot water supply services',
  ],
  '2': ['Electricity'],
  '3.1': [
    'Unprocessed rice',
    'Wheat',
    'Cereal grains',
    'Vegetables, fruits, nuts',
    'Oil seeds',
    'Sugar cane',
    'Plant-based fibers',
    'Crops',
    'Cattle',
    'Pigs',
    'Poultry',
    'Animals raised for meat',
    'Animal products',
    'Raw milk',
    'Raw wool and silk',
    'Manure',
    'Manure from biogas treatment',
    'Lumber',
    'Fishing gear',
    'Anthracite',
    'Coking Coal',
    'Other Bituminous Coal',
    'Sub-Bituminous Coal',
    'Patent fuel',
    'Lignite or brown coal',
    'Peat Brick',
    'Peat',
    'Crude petroleum and services related to crude oil extraction, excluding surveying',
    'Natural gas',
    'Natural gas liquids',
    'Other Hydrocarbons',
    'Uranium and thorium ores',
    'Iron ore',
    'Copper ore',
    'Nickel ore',
    'Aluminum ore',
    'Precious metal ore',
    'Lead, zinc and tin ore',
    'Other metal ores',
    'Stone',
    'Sand and clay',
    'Fertilizer',
    'Meat: beef',
    'Meat: pork',
    'Meat: poultry',
    'Other meat products',
    'Vegetable oils',
    'Dairy products',
    'Rice',
    'Sugar',
    'Processed food products',
    'Beverages',
    'Fish products',
    'Tobacco products',
    'Textiles',
    'Apparel / Clothing',
    'Leather and leather products: shoes, handbags, luggage',
    'Wood, cork, and straw products',
    'Wood recycling',
    'Wood pulp for paper making',
    'Paper recycling services',
    'Paper and paper products',
    'Books, pamphlets, posters, and printed packaging',
    'Coke(fuel)',
    'Gas Coke',
    'Coal Tar',
    'Gasoline',
    'Airplane gasoline',
    'Jet Fuel',
    'Kerosene jet fuel',
    'Kerosene',
    'Diesel gas oil',
    'Heavy Fuel Oil',
    'Refinery gas',
    'Liquefied Petroleum Gases(LPG)',
    'Refinery feedstocks',
    'Ethane',
    'Naphtha',
    'White Spirit & SBP',
    'Industrial lubricants',
    'Asphalt',
    'Paraffin wax products',
    'Petroleum coke',
    'Other petroleum products',
    'Nuclear fuel',
    'Plastic products, including polyester and nylon products',
    'Plastic recycling services',
    'Nitrogen fertilizer',
    'Phosphorus fertilizer',
    'Chemical products(beauty products and cleaning products)',
    'Charcoal',
    'Chemical additives and blending components',
    'Biogasoline',
    'Biodiesel',
    'Other Liquid Biofuels',
    'Rubber products',
    'Glass products',
    'Glass recycling',
    'Ceramic products',
    'Bricks and tiles',
    'Cement and plaster',
    'Ash for treatment',
    'Other non-metallic mineral products',
    'Iron and steel products',
    'Metal recycling services',
    'Precious metals',
    'Precious metals recycling',
    'Aluminum products',
    'Aluminum recycling',
    'Products of lead, zinc and tin',
    'Lead recycling',
    'Copper products',
    'Copper recycling',
    'Other non-ferrous metal products',
    'Other metals recycling',
    'Foundry services',
    'Secondary raw materials',
    'Bottle recycling',
    'Coke oven gas',
    'Blast Furnace Gas',
    'Oxygen Steel Furnace Gas',
    'Gas Works Gas',
    'Biogas',
    'Steam and hot water supply services',
    'Bottled, purified, or distilled water',
    'Construction materials recycling',
    'Car sales',
    'Retail services: motor fuel',
    'Car sales services',
    'Retail services',
    'Post and telecommunication services',
    'Financial services',
    'Insurance services',
    'Financial intermediation and supporting services',
    'Real estate services',
    'Machinery and equipment rental',
    'Computer services',
    'Research and development services',
    'Business services: consulting, photography, marketing, etc',
    'Public administration, social security services, and defence services',
    'Education services',
    'Health and social work services',
    'Membership organization services',
    'Recreational leagues and sporting federations',
    'Other services',
    'Domestic services',
    'Extra-territorial organizations and bodies',
  ],
  '3.2': [
    'Other metal products',
    'Other machinery and equipment',
    'Electronics',
    'Electrical machinery',
    'Radio and television equipment: cameras, recording equipment, microphones',
    'Precision instruments: watches and clocks, medical and optical equipment',
    'Motor vehicles',
    'Other transport equipment',
    'Furniture',
    'Construction work',
  ],
  '3.3': [
    'Anthracite',
    'Coking Coal',
    'Other Bituminous Coal',
    'Sub-Bituminous Coal',
    'Patent fuel',
    'Lignite or brown coal',
    'Peat Brick',
    'Peat',
    'Crude petroleum and services related to crude oil extraction, excluding surveying',
    'Natural gas',
    'Natural gas liquids',
    'Coke(fuel)',
    'Gas Coke',
    'Coal Tar',
    'Gasoline',
    'Airplane gasoline',
    'Jet Fuel',
    'Kerosene jet fuel',
    'Kerosene',
    'Diesel gas oil',
    'Heavy Fuel Oil',
    'Refinery gas',
    'Liquefied Petroleum Gases(LPG)',
    'Naphtha',
    'Petroleum coke',
    'Nuclear fuel',
    'Charcoal',
    'Biogasoline',
    'Biodiesel',
    'Other Liquid Biofuels',
    'Transmission services of electricity',
    'Electricity delivery services',
    'Coke oven gas',
    'Blast Furnace Gas',
    'Oxygen Steel Furnace Gas',
    'Gas Works Gas',
    'Biogas',
    'Gas fuels delivery services',
    'Steam and hot water supply services',
  ],
  '3.4': [
    'Railway transportation services',
    'Other land transportation services',
    'Transportation services via pipelines',
    'Sea and coastal water transportation services',
    'Inland water transportation services',
    'Air transport services',
  ],
  '3.5': [
    'Food waste, incinerated',
    'Paper waste, incinerated',
    'Plastic waste, incinerated',
    'Metal waste, incinerated',
    'Textile waste treatment, incinerated',
    'Wood, incinerated',
    'Oil waste, incinerated',
    'Food waste used for biogas',
    'Paper waste for biogas',
    'Sewage waste treatment for biogas',
    'Food waste, composted',
    'Paper and wood waste, composted',
    'Food waste for waste water treatment',
    'Wastewater treatment',
    'Food waste for landfill',
    'Paper waste for landfill',
    'Plastic waste for landfill',
    'Hazardous waste treatment',
    'Textile waste treatment for landfill',
    'Wood for landfill',
  ],
  '3.6': ['Hotel and restaurant services', 'Air transport services', 'Land travel: trains, taxis, rideshare, car rental'],
  '3.9': [
    'Car sales services',
    'Retail services',
    'Railway transportation services',
    'Other land transportation services',
    'Transportation services via pipelines',
    'Sea and coastal water transportation services',
    'Air transport services',
  ],
};
// Add new form_definition row data to the seeds array
const createEmissionScopes = (key: string, labels: Array<string>): Array<emission_scope> => {
  const parts = key.split('.');
  const scope = +parts[0];
  const sub_scope = +parts[1] ? +parts[1] : null;

  const scopes: Array<emission_scope> = labels.map(label => {
    return { id: new Cuid2Generator('scope').generate().scopedId, scope, sub_scope, label };
  });

  return scopes;
};

type emission_scope = {
  id?: string;
  scope: number;
  sub_scope?: number | null;
  label: string;
  created_at?: string;
  updated_at?: string;
};

export async function seedScopes() {
  await prisma.$connect();

  console.log(`Seeding Scopes...`);

  let count = 0;
  const keys = Object.keys(seeds);

  console.log(keys);
  for (const key of keys) {
    const scopes = createEmissionScopes(key, seeds[key]);
    for (const scope of scopes) {
      const result = await prisma.emission_scopes.upsert({
        where: {
          id: scope.id,
        },
        update: scope,
        create: {
          ...scope,
        },
      });

      count++;
      console.log(`🌱 seeded (${count} of ${scopes.length}) Scope: ${scope.label} 🌱`, result);
    }
  }

  console.log(`${count} Scopes seeded!`);

  await prisma.$disconnect();
}
