import { RegulationMap } from '@coldpbc/interfaces';
import { RegulationCategory, RegulationStatus, RegulationSubcategory, YesNo } from '@coldpbc/enums';

export const regulationsData: RegulationMap = {
  "h-152": {
    "Regulation": "H 152",
    "Bill Number": "H 152",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Vermont",
    "Effective": "2030",
    "Summary": "By 2024, prohibits paper food products and packaging containing PFAS. By 2030, prohibits all products containing PFAS.",
    "Category": RegulationCategory.Ban,
    "Subcategory": RegulationSubcategory.PFAs,
    "Product Type Eligibility": "Consumer products containing PFAS including textile and leather products",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Enforcement through Rhode Island's Department of Environmental Management; specific penalties not detailed in legislation",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products containing PFAS",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify products that might contain PFAS.",
      "2. Verify chemical content with suppliers.",
      "3. Phase out PFAS-containing products according to timeline."
    ],
    "Bill Text Link": "http://webserver.rilin.state.ri.us/BillText/BillText23/HouseText23/H5152.pdf"
  },
  "ab-1200": {
    "Regulation": "AB 1200",
    "Bill Number": "AB 1200",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - California",
    "Effective": "Current",
    "Summary": "Prohibits sale and distribution of products and packaging with added PFAS within California.",
    "Category": RegulationCategory.Ban,
    "Subcategory": RegulationSubcategory.PFAs,
    "Product Type Eligibility": "Food packaging made with plant fibers; cookware with intentionally added PFAS",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Enforcement through California's Unfair Competition Law with penalties up to $2,500 per violation",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of food packaging made with plant fibers; manufacturers of cookware",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. For cookware: Disclose on product label and online if the product contains intentionally added PFAS.",
      "2. For food packaging: Phase out PFAS in food packaging made with plant fibers.",
      "3. Verify compliance with suppliers."
    ],
    "Bill Text Link": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202120220AB1200"
  },
  "hd-3565": {
    "Regulation": "HD 3565",
    "Bill Number": "HD 3565",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Massachusetts",
    "Effective": "Current",
    "Summary": "Requires toxin reduction plans for substances like PFAS, lead, chromium, mercury, etc in packaging.",
    "Category": RegulationCategory.Ban,
    "Subcategory": RegulationSubcategory.PFAs,
    "Product Type Eligibility": "Various products including textiles apparel leather products with intentionally added PFAS",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations through Massachusetts enforcement mechanisms",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products containing intentionally added PFAS",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify products containing intentionally added PFAS.",
      "2. Develop phase-out plan.",
      "3. Work with suppliers on alternatives."
    ],
    "Bill Text Link": "https://malegislature.gov/Bills/192/HD3565"
  },
  "sb-0088": {
    "Regulation": "SB 0088",
    "Bill Number": "SB 0088",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Illinois",
    "Effective": "Current",
    "Summary": "Designates products without intentionally added PFAS chemicals as \"environmentally preferable supplies/services\" and prohibits sale of certain product categories that contain intentionally added PFAS chemicals.",
    "Category": RegulationCategory.Ban,
    "Subcategory": RegulationSubcategory.PFAs,
    "Product Type Eligibility": "Products containing intentionally added PFAS chemicals",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations; specific amounts vary by state",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products containing intentionally added PFAS",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify products containing intentionally added PFAS.",
      "2. Phase out affected products according to timeline.",
      "3. Work with suppliers on PFAS-free alternatives."
    ],
    "Bill Text Link": "https://www.billtrack50.com/billdetail/1454242"
  },
  "sb-0573": {
    "Regulation": "SB 0573",
    "Bill Number": "SB 0573",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Tennessee",
    "Effective": "Current",
    "Summary": "Requires producers to submit and implement a producer responsibility plan. Prohibits sale or distribution of any product that includes toxins like PFAs, lead, formeldahyde, etc.",
    "Category": RegulationCategory.Ban,
    "Subcategory": RegulationSubcategory.PFAs,
    "Product Type Eligibility": "Products containing intentionally added PFAS chemicals",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations; specific amounts not detailed in legislation",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products containing intentionally added PFAS",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify products containing intentionally added PFAS.",
      "2. Phase out affected products according to timeline.",
      "3. Work with suppliers on PFAS-free alternatives."
    ],
    "Bill Text Link": "https://www.billtrack50.com/billdetail/1463280"
  },
  "sb-76": {
    "Regulation": "SB 76",
    "Bill Number": "SB 76",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Nevada",
    "Effective": "Current",
    "Summary": "Prohibits sale or distribution of items including food packaging that contain intentionally added PFAS.",
    "Category": RegulationCategory.Ban,
    "Subcategory": RegulationSubcategory.PFAs,
    "Product Type Eligibility": "Products containing intentionally added PFAS chemicals",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations; specific amounts not detailed in legislation",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products containing intentionally added PFAS",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify products containing intentionally added PFAS.",
      "2. Phase out affected products according to timeline.",
      "3. Work with suppliers on PFAS-free alternatives."
    ],
    "Bill Text Link": "https://legiscan.com/GA/bill/SB76/2023"
  },
  "pfas-ny": {
    "Regulation": "New York PFAS Apparel Ban",
    "Bill Number": "S 1322 / A 994",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - New York",
    "Effective": "Current",
    "Summary": "",
    "Category": RegulationCategory.Ban,
    "Subcategory": RegulationSubcategory.PFAs,
    "Product Type Eligibility": "Apparel (clothing items intended to be worn on a person's body)",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties up to $1,000 for first violation and up to $2,500 for subsequent violations",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of apparel",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify apparel products that might contain PFAS.",
      "2. Work with suppliers to verify chemical content.",
      "3. For outdoor apparel for severe wet conditions (temporary exemption until 2028), ensure proper 'Made with PFAS Chemicals' labeling."
    ],
    "Bill Text Link": "https://www.nysenate.gov/legislation/bills/2023/S1322"
  },
  "hb-143": {
    "Regulation": "HB 143",
    "Bill Number": "HB 143",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Alaska",
    "Effective": "Passed",
    "Summary": "Aims to classify these facilities as manufacturers rather than waste management entities, thereby subjecting them to different environmental regulations.",
    "Category": RegulationCategory.EPR,
    "Subcategory": RegulationSubcategory.Recyclability,
    "Product Type Eligibility": "Products containing intentionally added PFAS chemicals",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations; specific amounts not detailed in legislation",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products containing intentionally added PFAS",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify products containing intentionally added PFAS.",
      "2. Phase out affected products according to timeline.",
      "3. Work with suppliers on PFAS-free alternatives."
    ],
    "Bill Text Link": "https://legiscan.com/NH/bill/HB143/2023"
  },
  "responsible-textile-recovery": {
    "Regulation": "The Responsible Textile Recovery Act",
    "Bill Number": "SB 707",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - California",
    "Effective": "2026",
    "Summary": "This law requires that a group of covered product producers come together and coordinate to form a Producer Responsibility Organization (PRO), which will be responsible for the collection, transportation, repair, sorting, recycling, and general safe and proper management of covered products at end of life. Covered producers, which may include brands, distributors, and retailers, must register with the PRO, submit data on sales volumes of covered products sold in California, and ultimately pay fees to the PRO that cover the full costs of the program, including costs of the product collection, sorting, and recycling programming, customer education, program administration, as well as state regulatory costs. Covered products under SB 707 include apparel and textile articles.",
    "Category": RegulationCategory.EPR,
    "Subcategory": RegulationSubcategory.Textiles,
    "Product Type Eligibility": "Apparel and textile articles",
    "Fee Explanation": "Fees will be determined by the PRO based on eco-modulation factors including durability, repairability, and recyclability",
    "Fees": "To be determined by PRO on a per-unit sales basis",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "To be determined in final regulations",
    "Revenue Applicability": "Excludes sellers with less than $1 million in annual aggregate global turnover",
    "Company Type Applicability": "Brands, distributors, and retailers of apparel and textile articles",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Track developments surrounding PRO application and selection.",
      "2. Prepare to join the approved PRO by July 1, 2026.",
      "3. Monitor CalRecycle regulations development."
    ],
    "Bill Text Link": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240SB707"
  },
  "plastic-pollution-prevention": {
    "Regulation": "Plastic Pollution Prevention and Packaging Producer Responsibility Act",
    "Bill Number": "SB 54",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - California",
    "Effective": "2025",
    "Summary": "The law requires by 2032 that CA cuts single-use packaging by 25%, recycles 65% of single-use packaging, and ensures that 100% of single-use packaging is recyclable or compostable.",
    "Category": RegulationCategory.EPR,
    "Subcategory": RegulationSubcategory.EPR,
    "Product Type Eligibility": "Packaging materials for products in all categories",
    "Fee Explanation": "Producers must pay fees to fund end-of-life management of packaging",
    "Fees": "Based on weight and recyclability of packaging; specific rates to be determined by PRO",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Administrative penalties for non-compliance",
    "Revenue Applicability": "No specific revenue threshold",
    "Company Type Applicability": "Producers of residential and commercial single-use packaging and plastic single-use food service ware",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Register with the Circular Action Alliance (CAA) as the PRO.",
      "2. Prepare to submit reporting data by August 31, 2025.",
      "3. Ensure packaging meets recyclable/compostable targets (100% by 2032)."
    ],
    "Bill Text Link": "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202120220SB54"
  },
  "epr-co": {
    "Regulation": "Producer Responsibility for Recycling Packaging and Paper",
    "Bill Number": "HB22-1355",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Colorado",
    "Effective": "2025",
    "Summary": "HB 22-1355 sets up a Producer Responsibility program that requires companies that sell products in packaging, paper products to fund a statewide recycling system to recycle those materials. These companies will form an independent non-profit organization, called a Producer Responsibility Organization, to coordinate, fund, and manage this statewide recycling system.",
    "Category": RegulationCategory.EPR,
    "Subcategory": RegulationSubcategory.EPR,
    "Product Type Eligibility": "Packaging materials and paper products",
    "Fee Explanation": "Producers must pay fees to fund statewide recycling system",
    "Fees": "Based on weight and recyclability of materials; specific rates to be determined by PRO",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Administrative penalties for non-compliance",
    "Revenue Applicability": "Exemptions may apply for producers with annual revenue under certain thresholds",
    "Company Type Applicability": "Companies that sell products in packaging or distribute paper products in Colorado",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Register with the Circular Action Alliance (CAA) as the PRO by October 1, 2024.",
      "2. Prepare to submit reporting data by August 31, 2025.",
      "3. Prepare to pay fees beginning January 2026."
    ],
    "Bill Text Link": "https://leg.colorado.gov/bills/hb22-1355"
  },
  "hb-1688": {
    "Regulation": "HB 1688",
    "Bill Number": "HB 1688",
    "In Effect": RegulationStatus.NotPassed,
    "Jurisdiction": "US - Hawaii",
    "Effective": "In Review",
    "Summary": "Sets the stage for EPR, by mandating the Department of Health to conduct a comprehensive statewide needs assessment to transition Hawaii toward a more circular economy, emphasizing waste reduction, reuse, and improved recycling infrastructure.",
    "Category": RegulationCategory.EPR,
    "Subcategory": RegulationSubcategory.EPR,
    "Product Type Eligibility": "Products containing intentionally added PFAS chemicals",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations; specific amounts not detailed in legislation",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products containing intentionally added PFAS",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify products containing intentionally added PFAS.",
      "2. Phase out affected products according to timeline.",
      "3. Work with suppliers on PFAS-free alternatives."
    ],
    "Bill Text Link": "https://app.leg.wa.gov/billsummary?BillNumber=1688&Year=2021"
  },
  "epr-me": {
    "Regulation": "Stewardship Program for Packaging",
    "Bill Number": "",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Maine",
    "Effective": "2026",
    "Summary": "In July 2021, the Maine legislature passed a law establishing a stewardship program for packaging. The program's purpose is to reduce the volume and toxicity and increase the recycling of packaging material. Producers of products will pay into a fund based on the amount and the recyclability of packaging associated with their products. These funds will be used to reimburse municipalities for eligible recycling and waste management costs, make investments in recycling infrastructure, and help Maine citizens understand how to recycle.",
    "Category": RegulationCategory.EPR,
    "Subcategory": RegulationSubcategory.EPR,
    "Product Type Eligibility": "Packaging materials for products in all categories",
    "Fee Explanation": "Producers must pay fees based on the amount and recyclability of packaging material used",
    "Fees": "Based on weight and recyclability of packaging; specific rates to be determined",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Administrative penalties for non-compliance",
    "Revenue Applicability": "Small producers may have reduced obligations or exemptions",
    "Company Type Applicability": "Brand owners, manufacturers, and importers of packaged products",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Monitor stewardship organization selection process.",
      "2. Prepare for registration requirements.",
      "3. Develop data collection systems for packaging materials."
    ],
    "Bill Text Link": "https://www.maine.gov/dep/waste/recycle/epr.html"
  },
  "epr-md": {
    "Regulation": "Packaging Materials Statewide Recycling Needs Assessment & Producer Responsibility",
    "Bill Number": "SB 222",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Maryland",
    "Effective": "",
    "Summary": "Under this legislature, the Maryland Department of the Environment is mandated to perform a statewide recycling needs assessment to support recommendations for establishing and implementing an EPR program in the State for packaging materials. Recommendations will be provided by MDE, in tandem with the producer responsibility advisory council, to the Governor and General Assembly.",
    "Category": RegulationCategory.EPR,
    "Subcategory": RegulationSubcategory.Recyclability,
    "Product Type Eligibility": "Packaging materials for products in all categories",
    "Fee Explanation": "Currently assessment phase; fee structures to be determined",
    "Fees": "To be determined following needs assessment",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "To be determined in final program implementation",
    "Revenue Applicability": "To be determined",
    "Company Type Applicability": "Producers of packaging materials",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Monitor development of the statewide recycling needs assessment.",
      "2. Prepare for potential future program requirements.",
      "3. Participate in stakeholder engagement opportunities."
    ],
    "Bill Text Link": "https://mgaleg.maryland.gov/mgawebsite/Legislation/Details/sb0222?ys=2023RS"
  },
  "ma-textile-waste-ban": {
    "Regulation": "Massachusetts Textile Waste Ban",
    "Bill Number": "310 CMR 19.000",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Massachusetts",
    "Effective": "Current",
    "Summary": "",
    "Category": RegulationCategory.EPR,
    "Subcategory": RegulationSubcategory.Textiles,
    "Product Type Eligibility": "Textiles including clothing, footwear, accessories, linens, and other fabric products",
    "Fee Explanation": "No direct fees to producers, but waste disposal facilities may charge for non-compliant disposal",
    "Fees": "No direct fees to producers",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for non-compliance with waste disposal regulations",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Any business generating textile waste; primary focus on waste generators rather than producers",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Develop strategies to divert textiles from regular waste streams.",
      "2. Establish relationships with textile recyclers or donation programs.",
      "3. Implement waste segregation practices. 4. Train staff on proper disposal methods."
    ],
    "Bill Text Link": "https://www.mass.gov/doc/310-cmr-19000-solid-waste-facility-regulations/download"
  },
  "s-2833": {
    "Regulation": "S 2833",
    "Bill Number": "S 2833",
    "In Effect": RegulationStatus.NotPassed,
    "Jurisdiction": "US - Massachusetts",
    "Effective": "In Review",
    "Summary": "An Act to Reduce Plastics, is comprehensive legislation aimed at mitigating plastic pollution and promoting environmental sustainability within the state.",
    "Category": RegulationCategory.EPR,
    "Subcategory": RegulationSubcategory.EPR,
    "Product Type Eligibility": "Products containing intentionally added PFAS chemicals",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations; specific amounts not detailed in legislation",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products containing intentionally added PFAS",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify products containing intentionally added PFAS.",
      "2. Phase out affected products according to timeline.",
      "3. Work with suppliers on PFAS-free alternatives."
    ],
    "Bill Text Link": "https://malegislature.gov/Bills/192/S2833"
  },
  "hb-5902": {
    "Regulation": "HB 5902",
    "Bill Number": "HB 5902",
    "In Effect": RegulationStatus.NotPassed,
    "Jurisdiction": "US - Michigan",
    "Effective": "In Review",
    "Summary": "Proposes the establishment of a Packaging Reduction and Recycling Program aimed at minimizing packaging waste and enhancing recycling efforts within the state.",
    "Category": RegulationCategory.EPR,
    "Subcategory": RegulationSubcategory.EPR,
    "Product Type Eligibility": "Products containing intentionally added PFAS chemicals",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations; specific amounts not detailed in legislation",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products containing intentionally added PFAS",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify products containing intentionally added PFAS.",
      "2. Phase out affected products according to timeline.",
      "3. Work with suppliers on PFAS-free alternatives."
    ],
    "Bill Text Link": "https://www.ilga.gov/legislation/billstatus.asp?DocNum=5902&GAID=16&GA=102&DocTypeID=HB&LegID=138223&SessionID=110"
  },
  "hf-3911": {
    "Regulation": "HF 3911",
    "Bill Number": "HF 3911",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Minnesota",
    "Effective": "2029",
    "Summary": "Establishes a statewide EPR program for packaging waste, requiring producers to fund recycling efforts and submit waste reduction plans annually.",
    "Category": RegulationCategory.EPR,
    "Subcategory": RegulationSubcategory.EPR,
    "Product Type Eligibility": "Packaging materials for products in all categories",
    "Fee Explanation": "Producers must pay fees to cover program costs based on material types and recyclability",
    "Fees": "Specific fee structure to be determined by PRO; based on material type, recyclability, and weight",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Administrative penalties for non-compliance",
    "Revenue Applicability": "Exemptions for businesses with less than $2 million in global gross revenues or less than one ton of covered material",
    "Company Type Applicability": "Producers of packaging materials and products sold in packaging",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Monitor PRO appointment process.",
      "2. Prepare to join appointed PRO by July 1, 2025.",
      "3. Prepare for funding obligations beginning 2029."
    ],
    "Bill Text Link": "https://www.revisor.mn.gov/bills/text.php?number=HF3911&version=0&session=ls93.0&session_year=2024&session_number=0&type=ccr"
  },
  "mn-packaging-waste": {
    "Regulation": "Minnesota's Packaging Waste and Cost Reduction Act",
    "Bill Number": "HF 3577",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Minnesota",
    "Effective": "2025",
    "Summary": "The law requires producers — generally the brand owner, manufacturer, or importer — to appoint and join a 501(c)3 nonprofit organization called a producer responsibility organization, to coordinate and fund the statewide program. Producers must join the appointed PRO by July 1, 2025. The program will begin in early 2029. Producers will be obligated to fund no less than 50% of the net costs of covered services for covered materials in the state beginning February 1, 2029; no less than 75% by 2030; and no less than 90% by 2031 and each year thereafter.",
    "Category": RegulationCategory.EPR,
    "Subcategory": RegulationSubcategory.EPR,
    "Product Type Eligibility": "Packaging materials for products in all categories",
    "Fee Explanation": "Producers must pay fees to cover program costs based on material types and recyclability",
    "Fees": "Specific fee structure to be determined by PRO; based on material type, recyclability, and weight",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Administrative penalties for non-compliance",
    "Revenue Applicability": "Exemptions for businesses with less than $2 million in global gross revenues or less than one ton of covered material",
    "Company Type Applicability": "Producers of packaging materials and products sold in packaging",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Monitor PRO appointment process.",
      "2. Prepare to join appointed PRO by July 1, 2025.",
      "3. Prepare for funding obligations beginning 2029."
    ],
    "Bill Text Link": "https://www.revisor.mn.gov/bills/bill.php?b=House&f=HF3577&ssn=0&y=2023"
  },
  "ccdaa": {
    "Regulation": "The Climate Corporate Data Accountability Act (CCDAA)",
    "Bill Number": "SB 253",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - California",
    "Effective": "2026",
    "Summary": "Requires companies doing business in California to disclose their scope 1, 2 and 3 emissions, and independently verify those calculations.",
    "Category": RegulationCategory.Reporting,
    "Subcategory": RegulationSubcategory.GHG,
    "Product Type Eligibility": "All products and services",
    "Fee Explanation": "Regulatory fees to be determined by CARB",
    "Fees": "To be determined by California Air Resources Board (CARB) by July 1 2025",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Administrative penalties for violations, to be determined by CARB",
    "Revenue Applicability": "$1 billion or more in annual revenue",
    "Company Type Applicability": "Public and private businesses doing business in California",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": ["1. Measure your entity's GHG emissions across all scopes.",
      "2. Have emissions independently verified.",
      "3. Submit data to CARB's online database when available. ",
      "4. Monitor CARB regulations, to be finalized by July 1, 2025."
    ],
    "Bill Text Link": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240SB253"
  },
  "pfas-mn": {
    "Regulation": "MN PFAS Ban (Amara's Law)",
    "Bill Number": "HF 2310",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Minnesota",
    "Effective": "2025",
    "Summary": "Bans the sale of certain products containing \"intentionally added\" per- and- polyfluoroalkyl substances (PFAS) starting Jan. 1, 2025. Any manufacturer selling products containing intentionally added PFAS in Minnesota must report on the PFAS and their purposes starting Jan. 1, 2026. On Jan. 1, 2032, all products which contain intentionally added PFAS, including pesticides and soil amendments, are prohibited unless the use of the PFAS in the product is determined to be a currently unavoidable use.",
    "Category": RegulationCategory.Ban,
    "Subcategory": RegulationSubcategory.PFAs,
    "Product Type Eligibility": "Products containing intentionally added PFAS chemicals, including textiles, cookware, and cosmetics",
    "Fee Explanation": "No direct fees, but requires reporting of PFAS use",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations; specific amounts not detailed in legislation",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers of products containing intentionally added PFAS",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Report presence of PFAS in any product to the MN Pollution Control Agency by January 1, 2026.",
      "2. Prepare for phased product bans.",
      "3. Develop alternative materials and formulations for affected products."
    ],
    "Bill Text Link": "https://www.revisor.mn.gov/bills/text.php?number=HF2310&type=bill&version=4&session=ls93&session_year=2023&session_number=0"
  },
  "ca-garment-worker-protection": {
    "Regulation": "California Garment Worker Protection Act",
    "Bill Number": "SB 62",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - California",
    "Effective": "Current",
    "Summary": "",
    "Category": RegulationCategory.Labor,
    "Subcategory": RegulationSubcategory.HumanRights,
    "Product Type Eligibility": "Apparel manufactured in California",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties up to $200 per employee per pay period for initial violations, up to $200,000 for subsequent violations; brand guarantors can be held jointly liable",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Garment manufacturers, contractors, brand guarantors who sell clothing made in California",
    "Employee Threshold Applicability": "Applies to any business with one or more employees in garment manufacturing",
    "Guidance & Steps to Comply": [
      "1. Ensure hourly wages for garment workers.",
      "2. Maintain accurate records of work performed.",
      "3. Establish systems to ensure contractors pay legal wages.",
      "4. Register with the Labor Commissioner's Office if manufacturing in California."
    ],
    "Bill Text Link": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202120220SB62"
  },
  "us-uyghur-forced-labor-prevention": {
    "Regulation": "US Uyghur Forced Labor Prevention Act (UFLPA)",
    "Bill Number": "Public Law No. 117-78 / Bill HR 6256",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Federal",
    "Effective": "Current",
    "Summary": "",
    "Category": RegulationCategory.Labor,
    "Subcategory": RegulationSubcategory.HumanRights,
    "Product Type Eligibility": "All products imported from Xinjiang Uyghur Autonomous Region (XUAR) or produced with labor from Xinjiang",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Seizure of goods, civil penalties, criminal prosecution for customs violations",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Any company importing goods from China, particularly from XUAR region or with supply chain links to the region",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Map your entire supply chain, including raw materials.",
      "2. Perform due diligence on suppliers.",
      "3. Implement traceability systems.",
      "4. Prepare documentation to demonstrate goods are not made with forced labor.",
      "5. Create an UFLPA compliance program."
    ],
    "Bill Text Link": "https://www.congress.gov/bill/117th-congress/house-bill/6256/text"
  },
  "ld-1503": {
    "Regulation": "LD 1503",
    "Bill Number": "LD 1503",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Maine",
    "Effective": "Current",
    "Summary": "All producers with PFAS-containing products that wish to sell in Maine must report by 1/1/23.",
    "Category": RegulationCategory.Requirement,
    "Subcategory": RegulationSubcategory.PFAs,
    "Product Type Eligibility": "All products with intentionally added PFAS, with specific focus initially on carpets, fabric treatments, and cookware",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations; specific amounts not specified",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products containing intentionally added PFAS",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify products containing intentionally added PFAS.",
      "2. Develop phase-out plan for affected products.",
      "3. For outdoor apparel for severe wet conditions (temporary exemption), ensure proper 'Made with PFAS Chemicals' labeling."
    ],
    "Bill Text Link": "https://legislature.maine.gov/bills/getPDF.asp?paper=HP1113&item=3&snum=130"
  },
  "ad-1817": {
    "Regulation": "California Safer Clothes and Textiles Act (PFAS regulation)",
    "Bill Number": "AB 1817",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - California",
    "Effective": "Current",
    "Summary": "The California Safer Clothes and Textiles Act (AB 1817), effective January 1, 2025, bans the manufacturing, distribution, and sale of new textiles containing regulated PFAS chemicals, with thresholds of 100 parts per million (ppm) in 2025, phasing down to 50 ppm in 2027.",
    "Category": RegulationCategory.Requirement,
    "Subcategory": RegulationSubcategory.PFAs,
    "Product Type Eligibility": "Textile articles including apparel, accessories, handbags, backpacks, draperies, furnishings, upholstery, bedding, towels, napkins, and tablecloths",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Enforced through California's Unfair Competition Law with penalties up to $2,500 per violation",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of textile articles",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify products that might contain PFAS.",
      "2. Work with suppliers to verify chemical content.",
      "3. Obtain certification that products contain no intentionally added PFAS.",
      "4. For outdoor apparel for severe wet conditions (temporary exemption until 2028), ensure proper 'Made with PFAS Chemicals' labeling."
    ],
    "Bill Text Link": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202120220AB1817"
  },
  "sb-219": {
    "Regulation": "Greenhouse gases: climate corporate accountability: climate-related financial risk",
    "Bill Number": "SB 219",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - California",
    "Effective": "2026",
    "Summary": "SB 219 amends certain climate disclosure requirements under Senate Bill 253, Climate Corporate Data Accountability Act (SB 253) and Senate Bill 261, Greenhouse Gases: Climate-Related Financial Risk (SB 261). As amended, neither bill requires reporting entities to pay an annual fee to the state of California upon filing their climate-related disclosures.",
    "Category": RegulationCategory.Reporting,
    "Subcategory": RegulationSubcategory.GHG,
    "Product Type Eligibility": "All products and services",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Administrative penalties for violations, to be determined by CARB",
    "Revenue Applicability": "Applies to businesses covered by SB 253 and SB 261",
    "Company Type Applicability": "Public and private businesses doing business in California subject to SB 253 and SB 261",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Monitor amendments to SB 253 and SB 261 implementation timelines.",
      "2. Prepare for climate reporting according to updated guidelines."
    ],
    "Bill Text Link": "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202320240SB219"
  },
  "ad-1305": {
    "Regulation": "the Voluntary Carbon Market Disclosures Business Regulation Act (VCMDA)",
    "Bill Number": "AB 1305",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - California",
    "Effective": "Current",
    "Summary": "Requires companies doing business in California who make claims regarding the achievement of net zero emissions, carbon neutral status, or significant carbon emission reductions to make disclosures on its website.",
    "Category": RegulationCategory.Reporting,
    "Subcategory": RegulationSubcategory.GHG,
    "Product Type Eligibility": "All products and services from companies making carbon emissions claims",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations through California's Unfair Competition Law",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Any business making claims regarding net zero emissions carbon neutral status or significant carbon emission reductions",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Disclose information about carbon offset purchases on website.",
      "2. Provide details on emission claims methodology.",
      "3. Ensure transparency in carbon accounting."
    ],
    "Bill Text Link": "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202320240AB1305"
  },
  "sec-climate-disclosure-rule": {
    "Regulation": "The Enhancement and Standardization of Climate-Related Disclosures for Investors",
    "Bill Number": "SEC Climate Disclosure Rule",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Federal",
    "Effective": "2026",
    "Summary": "Public companies are required to disclose their material Scope 1&2 GHG emissions.",
    "Category": RegulationCategory.Reporting,
    "Subcategory": RegulationSubcategory.GHG,
    "Product Type Eligibility": "All products and services",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "SEC enforcement actions, including civil penalties and other remedies",
    "Revenue Applicability": "Applies to public companies registered with the SEC",
    "Company Type Applicability": "Public companies subject to SEC reporting requirements",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "Note: Currently on hold pending legal challenges. If reinstated:",
      "1. Measure Scope 1 and 2 GHG emissions.",
      "2. Assess climate-related risks and impacts.",
      "3. Develop disclosure processes.",
      "4. Prepare for reporting according to phased implementation timeline."
    ],
    "Bill Text Link": "https://www.sec.gov/files/rules/other/2024/33-11120.pdf"
  },
  "sb-261": {
    "Regulation": "Climate-Related Financial Risk Act (CRFRA)",
    "Bill Number": "SB 261",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - California",
    "Effective": "",
    "Summary": "The California Climate-Related Financial Risk Act (SB 261) requires companies with over $500 million in annual revenue that do business in California to report on their climate-related financial risks and mitigation measures, starting January 1, 2026, and biennially thereafter.",
    "Category": RegulationCategory.Reporting,
    "Subcategory": RegulationSubcategory.ESG,
    "Product Type Eligibility": "All products and services",
    "Fee Explanation": "Not specified in current regulations",
    "Fees": "Not specified in current regulations",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Administrative penalties for violations, to be determined by CARB",
    "Revenue Applicability": "$500 million or more in annual revenue",
    "Company Type Applicability": "Public and private businesses doing business in California",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Familiarize with CARB's acceptable risk frameworks (pending).",
      "2. Develop timeline for completing climate-related financial risk reports.",
      "3. Prepare first report by January 1, 2026.",
      "4. Follow TCFD recommendations as guidance."
    ],
    "Bill Text Link": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240SB261"
  },
  "sb-253": {
    "Regulation": "California Climate Corporate Data Accountability Act",
    "Bill Number": "SB 253",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - California",
    "Effective": "2028",
    "Summary": "The California Climate Corporate Data Accountability Act (SB 253) requires large businesses (over $1 billion in annual revenue) doing business in California to publicly disclose their Scope 1, 2, and 3 greenhouse gas emissions annually, starting in 2026, following the Greenhouse Gas Protocol.",
    "Category": RegulationCategory.Reporting,
    "Subcategory": RegulationSubcategory.GHG,
    "Product Type Eligibility": "All products and services",
    "Fee Explanation": "Regulatory fees to be determined by CARB",
    "Fees": "To be determined by California Air Resources Board (CARB) by July 1 2025",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Administrative penalties for violations, to be determined by CARB",
    "Revenue Applicability": "$1 billion or more in annual revenue",
    "Company Type Applicability": "Public and private businesses doing business in California",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Measure your entity's GHG emissions across all scopes.",
      "2. Have emissions independently verified.",
      "3. Submit data to CARB's online database when available.",
      "4. Monitor CARB regulations, to be finalized by July 1, 2025."
    ],
    "Bill Text Link": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240SB253"
  },
  "ab-1201": {
    "Regulation": "AB 1201",
    "Bill Number": "AB 1201",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - California",
    "Effective": "Current",
    "Summary": "This bill requires that a product labeled \"compostable\" is third-party certified to actually breakdown into organic compost, doesn't contaminate compost (or the state's agricultural system) with toxic chemicals, and is readily identifiable to both consumers and solid waste facilities. AB 1201 also prohibits deceptive look-alike products.",
    "Category": RegulationCategory.Labeling,
    "Subcategory": RegulationSubcategory.Compostability,
    "Product Type Eligibility": "Products labeled as 'compostable' or 'home compostable'",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Enforcement through California's Unfair Competition Law with penalties up to $2,500 per violation",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products labeled as compostable",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Ensure products labeled as 'compostable' meet specific certification requirements.",
      "2. Obtain third-party certification from recognized organizations.",
      "3. Verify products don't contain intentionally added PFAS."
    ],
    "Bill Text Link": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202120220AB1201"
  },
  "ab-1544": {
    "Regulation": "AB 1544",
    "Bill Number": "AB 1544",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - New Jersey",
    "Effective": "Current",
    "Summary": "Prohobits sale, distribution, and import of certain products marketed as recyclable unless DEP determines they're widely recycled. Products with PFAS or other hazardous chemicals cannot be deemed recyclable.",
    "Category": RegulationCategory.Labeling,
    "Subcategory": RegulationSubcategory.Recyclability,
    "Product Type Eligibility": "Products labeled as 'compostable' or 'biodegradable'",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations of labeling requirements",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products with biodegradable or compostable claims",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Ensure products labeled as 'compostable' or 'biodegradable' meet specific certification requirements.",
      "2. Verify claims with proper scientific evidence.",
      "3. Review product labeling for compliance."
    ],
    "Bill Text Link": "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202320240AB1544"
  },
  "hb-0031": {
    "Regulation": "HB 0031",
    "Bill Number": "HB 0031",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Maryland",
    "Effective": "Current",
    "Summary": "Products and packaging that contain PFAS must not be labeled as recyclable. Establishes requirements for transparent labeling, marketing, and advertising for recycling products and packaging.",
    "Category": RegulationCategory.Labeling,
    "Subcategory": RegulationSubcategory.Recyclability,
    "Product Type Eligibility": "Products containing intentionally added PFAS chemicals",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations; specific amounts not detailed in legislation",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products containing intentionally added PFAS",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify products containing intentionally added PFAS.",
      "2. Phase out affected products according to timeline.",
      "3. Work with suppliers on PFAS-free alternatives."
    ],
    "Bill Text Link": "https://www.ilga.gov/legislation/billstatus.asp?DocNum=31&GAID=17&GA=103&DocTypeID=HB&LegID=142576&SessionID=112"
  },
  "hb-5086": {
    "Regulation": "HB 5086",
    "Bill Number": "HB 5086",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - New Hampshire",
    "Effective": "Current",
    "Summary": "Prohibits marketing or sale of consumer products labeled as \"compostable\" if the product has a total organic fluorine concentration of greater than 100PPM.",
    "Category": RegulationCategory.Labeling,
    "Subcategory": RegulationSubcategory.Compostability,
    "Product Type Eligibility": "Products containing intentionally added PFAS chemicals",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations; specific amounts not detailed in legislation",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products containing intentionally added PFAS",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify products containing intentionally added PFAS.",
      "2. Phase out affected products according to timeline.",
      "3. Work with suppliers on PFAS-free alternatives."
    ],
    "Bill Text Link": "https://www.legislature.mi.gov/documents/2021-2022/billintroduced/House/pdf/2022-HIB-5086.pdf"
  },
  "sb-0066": {
    "Regulation": "SB 0066",
    "Bill Number": "SB 0066",
    "In Effect": RegulationStatus.InEffect,
    "Jurisdiction": "US - Illinois",
    "Effective": "Current",
    "Summary": "Truth in Recycling Act. Prohibits deceptive or misleading claims about the recyclability of a product or packaging.",
    "Category": RegulationCategory.Labeling,
    "Subcategory": RegulationSubcategory.Recyclability,
    "Product Type Eligibility": "Products containing intentionally added PFAS chemicals",
    "Fee Explanation": "No direct fees",
    "Fees": "No direct fees",
    "Penalties (Beyond Fees)": YesNo.Yes,
    "Penalty Explanation": "Civil penalties for violations; specific amounts not detailed in legislation",
    "Revenue Applicability": "All businesses regardless of revenue",
    "Company Type Applicability": "Manufacturers, distributors, and retailers of products containing intentionally added PFAS",
    "Employee Threshold Applicability": "No specific employee threshold",
    "Guidance & Steps to Comply": [
      "1. Identify products containing intentionally added PFAS.",
      "2. Phase out affected products according to timeline.",
      "3. Work with suppliers on PFAS-free alternatives."
    ],
    "Bill Text Link": "https://www.billtrack50.com/billdetail/1435996"
  }
}
