-- First update the material names
UPDATE material_classification
SET name = 'Poly(methyl methacrylate) (PMMA) plastic'
WHERE name = 'Poly(methyl methacrylate) (PMMA) (Acrylic) plastic';

UPDATE material_classification
SET name = 'Polystyrene (PS) plastic'
WHERE name = 'Polysterene (PS) plastic';

-- Then update all the weight factors (converted to kg/m²)
-- UPDATE material_classification SET weight_factor = TBD WHERE name = 'Acetate, Triacetate fabric';
UPDATE material_classification SET weight_factor = 0.4 WHERE name = 'Acrylic fabric';
UPDATE material_classification SET weight_factor = 1.2 WHERE name = 'Acrylonitrile butadiene styrene (ABS) plastic';
UPDATE material_classification SET weight_factor = 0.3 WHERE name = 'Alpaca Fabric';
UPDATE material_classification SET weight_factor = 2.7 WHERE name = 'Aluminum';
UPDATE material_classification SET weight_factor = 0.5 WHERE name = 'Animal-based Leather Alternatives';
UPDATE material_classification SET weight_factor = 0.2 WHERE name = 'Aramid fabric';
UPDATE material_classification SET weight_factor = 0.05 WHERE name = 'BiComponent Coating';
UPDATE material_classification SET weight_factor = 0.1 WHERE name = 'BiComponent Laminate';
UPDATE material_classification SET weight_factor = 0.8 WHERE name = 'Bovine (cow) leather';
UPDATE material_classification SET weight_factor = 8.5 WHERE name = 'Brass';
UPDATE material_classification SET weight_factor = 1.5 WHERE name = 'Butyl rubber';
UPDATE material_classification SET weight_factor = 0.2 WHERE name = 'Carbon fiber fabric';
UPDATE material_classification SET weight_factor = 0.6 WHERE name = 'Cardboard';
UPDATE material_classification SET weight_factor = 1.4 WHERE name = 'Chloroprene rubber (Neoprene)';
UPDATE material_classification SET weight_factor = 7.19 WHERE name = 'Chromium';
UPDATE material_classification SET weight_factor = 8.96 WHERE name = 'Copper';
UPDATE material_classification SET weight_factor = 0.3 WHERE name = 'Cotton fabric';
UPDATE material_classification SET weight_factor = 0.1 WHERE name = 'Duck Down insulation';
UPDATE material_classification SET weight_factor = 0.2 WHERE name = 'Elastane/Spandex fabric';
UPDATE material_classification SET weight_factor = 1.2 WHERE name = 'Epoxy plastic';
UPDATE material_classification SET weight_factor = 1.3 WHERE name = 'Ethylene Propylene Diene Elastomer (EPDM)';
UPDATE material_classification SET weight_factor = 0.08 WHERE name = 'Ethylene-vinyl acetate (EVA) foam';
UPDATE material_classification SET weight_factor = 0.03 WHERE name = 'Expanded Polystyrene (EPS) foam';
UPDATE material_classification SET weight_factor = 0.25 WHERE name = 'Flax fiber fabric';
UPDATE material_classification SET weight_factor = 0.1 WHERE name = 'Foamed rubber';
UPDATE material_classification SET weight_factor = 0.3 WHERE name = 'Glass fiber fabric';
UPDATE material_classification SET weight_factor = 0.7 WHERE name = 'Goat leather';
UPDATE material_classification SET weight_factor = 19.32 WHERE name = 'Gold';
UPDATE material_classification SET weight_factor = 0.09 WHERE name = 'Goose Down Insulation';
UPDATE material_classification SET weight_factor = 0.25 WHERE name = 'Hemp fiber fabric';
UPDATE material_classification SET weight_factor = 7.8 WHERE name = 'Iron';
UPDATE material_classification SET weight_factor = 1.2 WHERE name = 'Isoprene Rubber (IR)';
UPDATE material_classification SET weight_factor = 0.3 WHERE name = 'Jute fiber fabric';
UPDATE material_classification SET weight_factor = 0.75 WHERE name = 'Kangaroo leather';
UPDATE material_classification SET weight_factor = 11.34 WHERE name = 'Lead';
UPDATE material_classification SET weight_factor = 0.25 WHERE name = 'Lyocell fabric';
UPDATE material_classification SET weight_factor = 1.738 WHERE name = 'Magnesium';
UPDATE material_classification SET weight_factor = 0.04 WHERE name = 'Microporous Coating';
UPDATE material_classification SET weight_factor = 0.09 WHERE name = 'Microporous Laminate';
UPDATE material_classification SET weight_factor = 0.25 WHERE name = 'Modal fabric';
UPDATE material_classification SET weight_factor = 0.06 WHERE name = 'Monolithic Coating';
UPDATE material_classification SET weight_factor = 0.1 WHERE name = 'Monolithic Laminate';
UPDATE material_classification SET weight_factor = 1 WHERE name = 'Natural Rubber (NR)';
UPDATE material_classification SET weight_factor = 8.9 WHERE name = 'Nickel';
UPDATE material_classification SET weight_factor = 1.3 WHERE name = 'Nitrile Rubber (NBR)';
UPDATE material_classification SET weight_factor = 0.2 WHERE name = 'Novel Polysaccharide fabric';
UPDATE material_classification SET weight_factor = 0.3 WHERE name = 'Nylon fabric';
UPDATE material_classification SET weight_factor = 1.1 WHERE name = 'Nylon/Polyamide (PA) plastic';
UPDATE material_classification SET weight_factor = 0.75 WHERE name = 'Pig leather';
UPDATE material_classification SET weight_factor = 0.4 WHERE name = 'Plant-based Leather Alternatives';
UPDATE material_classification SET weight_factor = 1 WHERE name = 'Plastic fillers';
UPDATE material_classification SET weight_factor = 21.45 WHERE name = 'Platinum';
UPDATE material_classification SET weight_factor = 1.2 WHERE name = 'Poly(methyl methacrylate) (PMMA) plastic';
UPDATE material_classification SET weight_factor = 1.2 WHERE name = 'Polybutadiene rubber (BR)';
UPDATE material_classification SET weight_factor = 1.2 WHERE name = 'Polycarbonate (PC) plastic';
UPDATE material_classification SET weight_factor = 0.3 WHERE name = 'Polyester fabric';
UPDATE material_classification SET weight_factor = 0.05 WHERE name = 'Polyester insulation';
UPDATE material_classification SET weight_factor = 1.4 WHERE name = 'Polyester plastic';
UPDATE material_classification SET weight_factor = 0.15 WHERE name = 'Polyethylene (PE) Fabric';
UPDATE material_classification SET weight_factor = 0.03 WHERE name = 'Polyethylene (PE) foam';
UPDATE material_classification SET weight_factor = 0.95 WHERE name = 'Polyethylene (PE) plastic';
UPDATE material_classification SET weight_factor = 0.04 WHERE name = 'Polyethylene terephthalate (PET) foam';
UPDATE material_classification SET weight_factor = 0.2 WHERE name = 'Polylactic Acid (PLA) fabric';
UPDATE material_classification SET weight_factor = 1.25 WHERE name = 'Polylactic Acid (PLA) plastic';
UPDATE material_classification SET weight_factor = 1.41 WHERE name = 'Polyoxymethylene (POM) plastic';
UPDATE material_classification SET weight_factor = 0.15 WHERE name = 'Polypropylene (PP) fabric';
UPDATE material_classification SET weight_factor = 0.9 WHERE name = 'Polypropylene (PP) plastic';
UPDATE material_classification SET weight_factor = 0.04 WHERE name = 'Polypropylene insulation';
UPDATE material_classification SET weight_factor = 1.05 WHERE name = 'Polystyrene (PS) plastic';
UPDATE material_classification SET weight_factor = 2.2 WHERE name = 'Polytetrafluoroethylene (PTFE) plastic';
UPDATE material_classification SET weight_factor = 0.28 WHERE name = 'Polytrimethylene terephthalate (PTT) fabric';
UPDATE material_classification SET weight_factor = 0.3 WHERE name = 'Polyurethane (PU) fabric';
UPDATE material_classification SET weight_factor = 0.03 WHERE name = 'Polyurethane (PU) foam';
UPDATE material_classification SET weight_factor = 0.4 WHERE name = 'Polyurethane (PU) synthetic leather';
UPDATE material_classification SET weight_factor = 1.19 WHERE name = 'Polyvinyl Acetate (PVA) plastic';
UPDATE material_classification SET weight_factor = 0.05 WHERE name = 'Polyvinyl chloride (PVC) foam';
UPDATE material_classification SET weight_factor = 1.4 WHERE name = 'Polyvinyl chloride (PVC) plastic';
UPDATE material_classification SET weight_factor = 0.75 WHERE name = 'Reptile leather';
UPDATE material_classification SET weight_factor = 0.1 WHERE name = 'Sheep Wool insulation';
UPDATE material_classification SET weight_factor = 1.2 WHERE name = 'Silicone plastic';
UPDATE material_classification SET weight_factor = 1.5 WHERE name = 'Silicone rubber';
UPDATE material_classification SET weight_factor = 0.15 WHERE name = 'Silk fabric';
UPDATE material_classification SET weight_factor = 10.49 WHERE name = 'Silver';
UPDATE material_classification SET weight_factor = 7.85 WHERE name = 'Steel';
UPDATE material_classification SET weight_factor = 1.2 WHERE name = 'Styrene-butadiene rubber (SBR)';
UPDATE material_classification SET weight_factor = 1 WHERE name = 'Thermoplastic elastomer (TPE)';
UPDATE material_classification SET weight_factor = 1.2 WHERE name = 'Thermoplastic Polyurethane (TPU) plastic';
UPDATE material_classification SET weight_factor = 1.3 WHERE name = 'Thermoplastic polyurethane (TPU) rubber';
UPDATE material_classification SET weight_factor = 1.2 WHERE name = 'Thermoset polyurethane (PU) plastic';
UPDATE material_classification SET weight_factor = 1.3 WHERE name = 'Thermoset polyurethane (PU) rubber';
UPDATE material_classification SET weight_factor = 7.31 WHERE name = 'Tin';
UPDATE material_classification SET weight_factor = 4.54 WHERE name = 'Titanium';
UPDATE material_classification SET weight_factor = 0.12 WHERE name = 'Typical EVA shoe compound';
UPDATE material_classification SET weight_factor = 1.3 WHERE name = 'Typical footwear rubber compound';
UPDATE material_classification SET weight_factor = 0.25 WHERE name = 'Viscose/Rayon fabric';
UPDATE material_classification SET weight_factor = 0.6 WHERE name = 'Wood';
UPDATE material_classification SET weight_factor = 0.3 WHERE name = 'Wool fabric';
UPDATE material_classification SET weight_factor = 7.14 WHERE name = 'Zinc';
