import { extendApi, extendZodWithOpenApi } from '@anatine/zod-openapi';
import * as z from 'zod';

import { CategorySchema } from './categorySchema';
extendZodWithOpenApi(z);

export const CategoryDefinitionSchema = z.object({
  climate_leadership: CategorySchema.openapi({ title: 'Climate Leadership' }),
  employee_engagement: CategorySchema.openapi({ title: 'Employee Engagement' }),
  company_decarbonization: CategorySchema.openapi({ title: 'Company Decarbonization' }),
  cold_score: z
    .number({
      description: 'The cold score of the company',
    })
    .int()
    .min(0)
    .nullable()
    .optional(),
});

export const CreateCategoryDefinitionItemSchema = z.object({
  name: z.string().openapi({ title: 'The name of the resource', description: 'Must be unique' }),
  definition: CategoryDefinitionSchema.openapi({ title: 'The json definition of the resource', description: 'This is required' }),
  description: z.string().openapi({ title: 'The description of the resource', description: 'This is optional' }),
  created_at: z.date().optional().openapi({ title: 'The date the resource was created', description: 'This is generated by the server' }),
  updated_at: z.date().optional().openapi({ title: 'The date the resource was updated', description: 'This is generated by the server' }),
});

export type ZodCreateCategoryDefinitionItemDto = z.infer<typeof CreateCategoryDefinitionItemSchema>;

export const CategoryDefinitionItemSchema = CreateCategoryDefinitionItemSchema.extend({
  id: z.string().uuid().openapi({ title: 'The id of the resource', description: 'This is generated by the server' }),
  created_at: z.date().openapi({ title: 'The date the resource was created', description: 'This is generated by the server' }),
  updated_at: z.date().openapi({ title: 'The date the resource was updated', description: 'This is generated by the server' }),
});

export type ZodCategoryDefinitionItemDto = z.infer<typeof CategoryDefinitionItemSchema>;
