export function getStripeProductsMock() {
	return {
		object: 'list',
		data: [
			{
				id: 'prod_QkIRwzMMhHIiTL',
				object: 'product',
				active: true,
				attributes: [],
				created: 1724859137,
				default_price: 'price_1Psnr3FjHElEUwepzQDnRi0k',
				description: 'Subscription to the Cold Standard service plan',
				images: [],
				livemode: false,
				marketing_features: [],
				metadata: {},
				name: 'Cold Standard Test',
				package_dimensions: null,
				shippable: null,
				statement_descriptor: null,
				tax_code: 'txcd_10000000',
				type: 'service',
				unit_label: null,
				updated: 1724957575,
				url: null,
			},
			{
				id: 'prod_QkIRJ32rOZOxxt',
				object: 'product',
				active: true,
				attributes: [],
				created: 1724859107,
				default_price: 'price_1PsnqZFjHElEUwepWpIbVBvi',
				description: 'Subscription to the Cold Premium service plan',
				images: [],
				livemode: false,
				marketing_features: [],
				metadata: {},
				name: 'Cold Premium Test',
				package_dimensions: null,
				shippable: null,
				statement_descriptor: null,
				tax_code: 'txcd_10000000',
				type: 'service',
				unit_label: null,
				updated: 1724957590,
				url: null,
			},
		],
		has_more: false,
		url: '/v1/products',
	};
}

export function getCustomerWithSubscriptionMock() {
	return {
		currentSubscription: {
			id: 'sub_1Puh46FjHElEUwepHvem0Bfp',
			object: 'subscription',
			application: null,
			application_fee_percent: null,
			automatic_tax: {
				enabled: true,
				liability: {
					type: 'self',
				},
			},
			billing_cycle_anchor: 1725309694,
			billing_cycle_anchor_config: null,
			billing_thresholds: null,
			cancel_at: null,
			cancel_at_period_end: false,
			canceled_at: null,
			cancellation_details: {
				comment: null,
				feedback: null,
				reason: null,
			},
			collection_method: 'charge_automatically',
			created: 1725309694,
			currency: 'usd',
			current_period_end: 1727901694,
			current_period_start: 1725309694,
			customer: 'cus_Ql2VfJKu4fRyTt',
			days_until_due: null,
			default_payment_method: null,
			default_source: null,
			default_tax_rates: [],
			description: null,
			discount: null,
			discounts: [],
			ended_at: null,
			invoice_settings: {
				account_tax_ids: null,
				issuer: {
					type: 'self',
				},
			},
			items: {
				object: 'list',
				data: [
					{
						id: 'si_QmFZsW94JJoWRK',
						object: 'subscription_item',
						billing_thresholds: null,
						created: 1725309694,
						discounts: [],
						metadata: {},
						plan: {
							id: 'price_1Psnr3FjHElEUwepzQDnRi0k',
							object: 'plan',
							active: true,
							aggregate_usage: null,
							amount: 25000,
							amount_decimal: '25000',
							billing_scheme: 'per_unit',
							created: 1724859137,
							currency: 'usd',
							interval: 'month',
							interval_count: 1,
							livemode: false,
							metadata: {},
							meter: null,
							nickname: null,
							product: 'prod_QkIRwzMMhHIiTL',
							tiers_mode: null,
							transform_usage: null,
							trial_period_days: null,
							usage_type: 'licensed',
						},
						price: {
							id: 'price_1Psnr3FjHElEUwepzQDnRi0k',
							object: 'price',
							active: true,
							billing_scheme: 'per_unit',
							created: 1724859137,
							currency: 'usd',
							custom_unit_amount: null,
							livemode: false,
							lookup_key: null,
							metadata: {},
							nickname: null,
							product: 'prod_QkIRwzMMhHIiTL',
							recurring: {
								aggregate_usage: null,
								interval: 'month',
								interval_count: 1,
								meter: null,
								trial_period_days: null,
								usage_type: 'licensed',
							},
							tax_behavior: 'unspecified',
							tiers_mode: null,
							transform_quantity: null,
							type: 'recurring',
							unit_amount: 25000,
							unit_amount_decimal: '25000',
						},
						quantity: 1,
						subscription: 'sub_1Puh46FjHElEUwepHvem0Bfp',
						tax_rates: [],
					},
				],
				has_more: false,
				total_count: 1,
				url: '/v1/subscription_items?subscription=sub_1Puh46FjHElEUwepHvem0Bfp',
			},
			latest_invoice: 'in_1Puh46FjHElEUwepoB10ooDQ',
			livemode: false,
			metadata: {},
			next_pending_invoice_item_invoice: null,
			on_behalf_of: null,
			pause_collection: null,
			payment_settings: {
				payment_method_options: null,
				payment_method_types: null,
				save_default_payment_method: 'off',
			},
			pending_invoice_item_interval: null,
			pending_setup_intent: null,
			pending_update: null,
			plan: {
				id: 'price_1Psnr3FjHElEUwepzQDnRi0k',
				object: 'plan',
				active: true,
				aggregate_usage: null,
				amount: 25000,
				amount_decimal: '25000',
				billing_scheme: 'per_unit',
				created: 1724859137,
				currency: 'usd',
				interval: 'month',
				interval_count: 1,
				livemode: false,
				metadata: {},
				meter: null,
				nickname: null,
				product: 'prod_QkIRwzMMhHIiTL',
				tiers_mode: null,
				transform_usage: null,
				trial_period_days: null,
				usage_type: 'licensed',
			},
			quantity: 1,
			schedule: null,
			start_date: 1725309694,
			status: 'active',
			test_clock: null,
			transfer_data: null,
			trial_end: null,
			trial_settings: {
				end_behavior: {
					missing_payment_method: 'create_invoice',
				},
			},
			trial_start: null,
		},
		paymentMethod: {
			id: 'pm_1Pug9vFjHElEUwepjLLZA6KV',
			object: 'payment_method',
			allow_redisplay: 'always',
			billing_details: {
				address: {
					city: null,
					country: 'US',
					line1: null,
					line2: null,
					postal_code: '12345',
					state: null,
				},
				email: null,
				name: null,
				phone: null,
			},
			card: {
				brand: 'visa',
				checks: {
					address_line1_check: null,
					address_postal_code_check: 'pass',
					cvc_check: 'pass',
				},
				country: 'US',
				display_brand: 'visa',
				exp_month: 12,
				exp_year: 2034,
				fingerprint: 'nsDS7vlfkudMShid',
				funding: 'debit',
				generated_from: null,
				last4: '5556',
				networks: {
					available: ['visa'],
					preferred: null,
				},
				three_d_secure_usage: {
					supported: true,
				},
				wallet: null,
			},
			created: 1725306211,
			customer: 'cus_Ql2VfJKu4fRyTt',
			livemode: false,
			metadata: {},
			radar_options: {},
			type: 'card',
		},
	};
}

export function getCustomerWithOutSubscriptionMock() {
	return {
		currentSubscription: null,
		paymentMethod: null,
	};
}

export function getPortalSessionMock() {
	return {
		id: 'bps_1Pv0baFjHElEUwepqTWx7QxZ',
		object: 'billing_portal.session',
		configuration: 'bpc_1PtassFjHElEUwepPDoNe8Vo',
		created: 1725384806,
		customer: 'cus_Ql2VfJKu4fRyTt',
		flow: {
			after_completion: {
				hosted_confirmation: {
					custom_message: null,
				},
				redirect: null,
				type: 'hosted_confirmation',
			},
			subscription_cancel: null,
			subscription_update: null,
			subscription_update_confirm: null,
			type: 'payment_method_update',
		},
		livemode: false,
		locale: null,
		on_behalf_of: null,
		return_url: 'http://localhost:4200/settings/billing',
		url: 'https://billing.stripe.com/p/session/test_YWNjdF8xTlRtcmRGakhFbEVVd2VwLF9RbVpsRmxLZDdvUEZ0STZoVkpNaGtscDNWdkFCTmND0100DBlqHaBD/flow',
	};
}
